export const FEATURES = [
  ['Favoritos à mão', 'Uma aba própria e um atalho na ficha para manter as pessoas especiais sempre perto.', 'catalog'],
  ['Arquivo organizado', 'Guarde fichas fora da lista principal e restaure quando quiser.', 'catalog'],
  ['Lixeira recuperável', 'Fotos, notas, histórias, lembretes e posições continuam protegidos para restauração.', 'catalog'],
  ['Organização em lote', 'Aplique tags, categorias, pastas, favoritos e ações em várias fichas de uma vez.', 'catalog'],
  ['Filtros salvos', 'Salve, renomeie e reutilize combinações de busca.', 'catalog'],
  ['Busca global', 'Ctrl+K encontra pessoas, apelidos, contatos, tags, páginas e ações.', 'home'],
  ['Rascunhos recuperáveis', 'Cadastro, edição e fichário rápido preservam o que ainda não foi publicado.', 'drafts'],
  ['Lembretes editáveis', 'Defina data, pessoa, prioridade e detalhes. Conclua ou reagende quando quiser.', 'reminders'],
  ['Modo privacidade', 'Ctrl+Shift+P cobre as informações na hora. O PIN é opcional.', 'settings'],
  ['Categorias do seu jeito', 'Crie e renomeie categorias e subcategorias preservando vínculos.', 'taxonomy'],
  ['Localizações reutilizáveis', 'Cadastre bairros e cidades para preencher fichas com mais rapidez.', 'taxonomy'],
  ['Tags com identidade', 'Crie, renomeie e escolha cores para tags próprias.', 'taxonomy'],
  ['Nomes e apelidos', 'Edite nomes de pessoas, perfil, usuário de acesso e tierlists.', 'catalog'],
  ['Possíveis duplicatas', 'Revise coincidências de nome, telefone ou contato sem mesclagens automáticas.', 'duplicates'],
  ['Cópias independentes', 'Duplique fichas, quadros ou tierlists sem alterar a original.', 'tierlists'],
  ['Exportação CSV', 'Exporte resultados filtrados ou apenas as fichas selecionadas.', 'catalog'],
  ['Desfazer e refazer', 'Recupere até 20 alterações nesta sessão.', 'home'],
  ['Pontos de restauração', 'Guarde até cinco versões locais e baixe cópias externas.', 'settings'],
  ['Salvamento transparente', 'IndexedDB, cópia pendente e indicador real de gravação.', 'settings'],
  ['Upload em lote', 'Arraste várias imagens, valide e otimize antes de guardar.', 'gallery'],
  ['Galeria por pastas', 'Organize fotos por pessoa, tipo, data, pasta e seleção múltipla.', 'gallery'],
  ['Fotos em tela cheia', 'Amplie, navegue com setas, vincule e classifique sem sair da galeria.', 'gallery'],
  ['Pastas mistas', 'Reúna pessoas, fotos, notas e histórias sem duplicar os itens.', 'folders'],
  ['Notas gerais', 'Guarde ideias, referências e lembretes fora das fichas.', 'notes'],
  ['Quadro de investigação', 'Conecte pistas, fichas, notas e pastas em etapas pessoais.', 'board'],
  ['Nível de amizade', 'Registre proximidade sem mexer na nota geral.', 'add'],
  ['Estilo e características', 'Mais opções de cabelo, tipo de corpo e estilo de roupa.', 'add'],
  ['Tags de aparência adultas', 'Use classificações pessoais apenas em fichas verificadas como adultas.', 'add'],
  ['Fichas a completar', 'Veja o progresso de cada ficha e filtre as que precisam de detalhes.', 'catalog'],
  ['Tierlists reordenáveis', 'Mova pessoas, reordene faixas e personalize cores e nomes.', 'tierlists'],
  ['Impressão organizada', 'Imprima fichas e rankings, ou salve em PDF pelo navegador.', 'ranking'],
  ['Acessibilidade de leitura', 'Aumente textos ou reduza animações nas preferências.', 'settings'],
] as const;