
/**
 * Recursos adicionados nesta atualização. Cada item leva à tela onde ele vive.
 * A lista antiga (FEATURES) continua intacta logo abaixo.
 */
export const NEW_FEATURES: [string, string, string][] = [
  ['Abas do catálogo consertadas', 'As abas Todas/Favoritos/Arquivadas/Lixeira dobram, grudam no topo e mostram sempre a contagem certa, mesmo com centenas de fichas e fotos.', 'catalog'],
  ['Catálogo que não trava com fotos', 'A lista é carregada em páginas, as imagens só baixam quando aparecem e o rascunho não regrava tudo a cada letra.', 'catalog'],
  ['Fechamento sem bloqueio', 'Fechar ou recarregar a aba não mostra mais aquele aviso eterno quando o catálogo é grande.', 'settings'],
  ['Favoritas mostram tudo', 'A aba Favoritos inclui também fichas arquivadas, como a contagem já prometia.', 'catalog'],
  ['Modelos de cadastro preservados', 'Os modelos salvos voltam a aparecer depois de fechar o aplicativo (eles eram perdidos na leitura dos dados).', 'add'],
  ['Painel com gráficos', 'Pizza por categoria, barras por faixa de nota e idade, média geral e completude em uma tela só.', 'dashboard'],
  ['Radar de atributos', 'Gráfico de aranha com os oito critérios, comparando uma pessoa com a média do catálogo.', 'dashboard'],
  ['Histórico de notas', 'Cada mudança de avaliação é registrada com data e vira uma linha do tempo na ficha.', 'catalog'],
  ['Relatório do mês', 'Quantas pessoas você adicionou, quantas interações registrou e quantas fotos entraram no mês.', 'dashboard'],
  ['Mapa por bairro e cidade', 'Agrupamento por localização com média de cada lugar; um clique filtra o catálogo.', 'dashboard'],
  ['Comparar categorias', 'Escola, igreja, FSY, trabalho: qual origem tem a melhor média, em ranking.', 'dashboard'],
  ['Campeã do mês', 'Destaque automático da ficha mais bem pontuada e da mais vista no mês.', 'dashboard'],
  ['Batalha de categorias', 'Placar direto entre as origens, com contagem de pessoas e nota média.', 'dashboard'],
  ['Raridade', 'Comum, Raro, Épico e Lendário: sugerido pela nota e ajustável na ficha.', 'catalog'],
  ['XP e nível do catálogo', 'Você sobe de nível cadastrando, fotografando, escrevendo e concluindo metas.', 'dashboard'],
  ['Conquistas', '22 medalhas, de “primeira conexão” a “carta lendária”, com aviso ao desbloquear.', 'dashboard'],
  ['Desafios semanais', 'Metas curtas da semana com barra de progresso no painel.', 'dashboard'],
  ['Modo swipe', 'Passe os cartões para a direita (favorita) ou esquerda (passa), com atalhos de seta.', 'discover'],
  ['This or That', 'Duelo entre duas fichas; as vitórias formam um placar automático.', 'discover'],
  ['Radar do duelo', 'Comparação lado a lado com gráfico de aranha das duas pessoas.', 'discover'],
  ['Busca avançada combinada', 'Nota mínima + tag + cabelo + altura + faixa de idade + raridade + pasta, tudo junto.', 'catalog'],
  ['Sugestões de tags', 'Ao cadastrar, o catálogo sugere as etiquetas mais usadas naquela categoria.', 'add'],
  ['Salvar e adicionar outra', 'Cadastro em sequência sem perder o ritmo.', 'add'],
  ['Aniversário e idade automática', 'Informe a data e a idade é calculada; o aviso de aniversário entra na central.', 'add'],
  ['Campos personalizados', 'Crie os campos que quiser (signo, profissão, time) e eles entram na busca.', 'add'],
  ['Anexos por pessoa', 'Links, vídeos, PDFs e áudios guardados na ficha, com validação de endereço.', 'add'],
  ['Favoritar fotos', 'Coração em cada foto da galeria e filtro só de favoritas.', 'gallery'],
  ['Álbuns de fotos', 'Reúna imagens de várias pessoas por evento ou viagem, sem mover arquivos.', 'gallery'],
  ['Detector de duplicatas', 'Acha fotos repetidas pela impressão digital do arquivo e remove as cópias com um clique.', 'gallery'],
  ['Antes e depois', 'Duas fotos com divisor deslizante para comparar na hora.', 'gallery'],
  ['Pastas com subpastas', 'Aninhe pastas, arraste uma sobre a outra, fixe no topo, escolha capa e ordenação.', 'folders'],
  ['Busca de pastas', 'Ache qualquer pasta pelo nome e veja quantos itens ela reúne, incluindo as filhas.', 'folders'],
  ['Notificações de verdade', 'Permissão do navegador, central de avisos com histórico e checagem a cada minuto.', 'settings'],
  ['Radar de prazos', 'Aviso quando falta pouco para um lembrete, compromisso ou meta, e quando faz tempo que você não vê alguém.', 'reminders'],
  ['Lembretes que se repetem', 'Diário, semanal, mensal ou anual: ao concluir, o lembrete já é reagendado.', 'reminders'],
  ['Agenda de encontros', 'Compromissos com local e hora, cronômetro do encontro e histórico de conversas.', 'agenda'],
  ['Meu espaço pessoal', 'Diário com humor, metas, links próprios e um cofre de fotos com PIN separado.', 'myspace'],
  ['Modo pânico', 'Três Esc seguidos (ou Ctrl+Shift+P) escondem tudo na hora.', 'settings'],
  ['Modo disfarce', 'Atalho B desfoca fotos e nomes até você passar o mouse.', 'settings'],
  ['Cores personalizadas', 'Escolha a cor de destaque do tema, aplicada na hora em todo o app.', 'settings'],
  ['Multi-perfis reais', 'Vários catálogos no mesmo dispositivo, cada um com seus dados.', 'settings'],
  ['Capítulos nas fanfics', 'Divida a história em capítulos numerados, reordene e edite cada um.', 'stories'],
  ['Modo leitura focada', 'Tela limpa, texto grande e sem distrações para ler o que você escreveu.', 'stories'],
  ['Estatísticas de texto', 'Palavras, caracteres e tempo de leitura em cada história.', 'stories'],
  ['Exportar histórias', 'Markdown, página web, EPUB de verdade ou impressão em PDF.', 'stories'],
  ['Foto aleatória na abertura', 'Uma capa com uma foto do seu catálogo ao entrar (opcional).', 'settings'],
  ['Atalhos novos', 'D painel, A agenda, M meu espaço, X descobrir, G galeria, B disfarce.', 'guide'],
  ['Busca global ampliada', 'Ctrl+K agora acha notas, histórias, lembretes e fotos, além de pessoas e ações.', 'home'],
  ['Densidade compacta', 'Mais itens por tela em todo o aplicativo, não só no catálogo.', 'settings'],
  ['Limpeza programada da lixeira', 'Defina após quantos dias as fichas da lixeira podem ser limpas, com aviso antes.', 'settings'],
];

export const FEATURES = [
  ['Favoritos à mão', 'Uma aba própria e um atalho na ficha para manter as pessoas especiais sempre perto.', 'catalog'],
  ['Arquivo organizado', 'Guarde fichas fora da lista principal e restaure quando quiser.', 'catalog'],
  ['Lixeira recuperável', 'Fotos, notas, histórias, lembretes e posições continuam protegidos para restauração.', 'catalog'],
  ['Organização em lote', 'Aplique tags, categorias, pastas, favoritos e ações em várias fichas de uma vez.', 'catalog'],
  ['Filtros salvos', 'Salve, renomeie e reutilize combinações de busca.', 'catalog'],
  ['Busca global', 'Ctrl+K encontra pessoas, apelidos, contatos, tags, páginas e ações.', 'home'],
  ['Rascunhos recuperáveis', 'Cadastro, edição e fichário rápido preservam o que ainda não foi publicado.', 'drafts'],
  ['Lembretes editáveis', 'Defina data, pessoa, prioridade e detalhes. Conclua ou reagende quando quiser.', 'reminders'],
  ['Modo privacidade', 'Ctrl+Shift+P cobre as informações na hora. O PIN é opcional.', 'settings'],
  ['Categorias do seu jeito', 'Crie e renomeie categorias e subcategorias preservando vínculos.', 'taxonomy'],
  ['Localizações reutilizáveis', 'Cadastre bairros e cidades para preencher fichas com mais rapidez.', 'taxonomy'],
  ['Tags com identidade', 'Crie, renomeie e escolha cores para tags próprias.', 'taxonomy'],
  ['Nomes e apelidos', 'Edite nomes de pessoas, perfil, usuário de acesso e tierlists.', 'catalog'],
  ['Possíveis duplicatas', 'Revise coincidências de nome, telefone ou contato sem mesclagens automáticas.', 'duplicates'],
  ['Cópias independentes', 'Duplique fichas, quadros ou tierlists sem alterar a original.', 'tierlists'],
  ['Exportação CSV', 'Exporte resultados filtrados ou apenas as fichas selecionadas.', 'catalog'],
  ['Desfazer e refazer', 'Recupere até 20 alterações nesta sessão.', 'home'],
  ['Pontos de restauração', 'Guarde até cinco versões locais e baixe cópias externas.', 'settings'],
  ['Salvamento transparente', 'IndexedDB, cópia pendente e indicador real de gravação.', 'settings'],
  ['Upload em lote', 'Arraste várias imagens, valide e otimize antes de guardar.', 'gallery'],
  ['Galeria por pastas', 'Organize fotos por pessoa, tipo, data, pasta e seleção múltipla.', 'gallery'],
  ['Fotos em tela cheia', 'Amplie, navegue com setas, vincule e classifique sem sair da galeria.', 'gallery'],
  ['Pastas mistas', 'Reúna pessoas, fotos, notas e histórias sem duplicar os itens.', 'folders'],
  ['Notas gerais', 'Guarde ideias, referências e lembretes fora das fichas.', 'notes'],
  ['Quadro de investigação', 'Conecte pistas, fichas, notas e pastas em etapas pessoais.', 'board'],
  ['Nível de amizade', 'Registre proximidade sem mexer na nota geral.', 'add'],
  ['Estilo e características', 'Mais opções de cabelo, tipo de corpo e estilo de roupa.', 'add'],
  ['Tags de aparência adultas', 'Use classificações pessoais apenas em fichas verificadas como adultas.', 'add'],
  ['Fichas a completar', 'Veja o progresso de cada ficha e filtre as que precisam de detalhes.', 'catalog'],
  ['Tierlists reordenáveis', 'Mova pessoas, reordene faixas e personalize cores e nomes.', 'tierlists'],
  ['Impressão organizada', 'Imprima fichas e rankings, ou salve em PDF pelo navegador.', 'ranking'],
  ['Acessibilidade de leitura', 'Aumente textos ou reduza animações nas preferências.', 'settings'],
] as const;