
/**
 * Recursos adicionados nesta atualização. Cada item leva à tela onde ele vive.
 * A lista antiga (FEATURES) continua intacta logo abaixo.
 */
export const NEW_FEATURES: [string, string, string][] = [
  ['Navegação feita para celular', 'Uma barra inferior mantém Início, Catálogo, Adicionar, Buscar e Menu ao alcance do polegar.', 'home'],
  ['Menu lateral deslizante', 'No celular e tablet, o menu abre por cima da tela, fecha ao tocar fora e não espreme mais o conteúdo.', 'home'],
  ['Central de ações rápidas', 'O botão de raio reúne mais de vinte atalhos úteis com contagens atualizadas. No computador, use também a tecla Q.', 'home'],
  ['Fichário com um toque', 'O botão central da barra inferior abre o cadastro rápido sem precisar percorrer menus.', 'add'],
  ['Busca móvel sempre à mão', 'A busca global ganhou lugar fixo na barra inferior e pesquisa fichas, notas, histórias, fotos e ações.', 'home'],
  ['Filtro “sem foto” instantâneo', 'Encontre em um toque as fichas que ainda precisam de imagem pela central rápida.', 'catalog'],
  ['Filtro de fichas incompletas', 'Abra os cadastros menos completos primeiro e continue exatamente onde falta informação.', 'catalog'],
  ['Atalho para melhores notas', 'Mostre automaticamente as fichas com nota 4 ou superior, ordenadas da maior para a menor.', 'catalog'],
  ['Resumo copiável', 'Gere e copie um resumo com os totais do catálogo para usar em qualquer outro aplicativo.', 'home'],
  ['Compartilhar pelo celular', 'Envie o resumo usando a folha nativa de compartilhamento do Android, iPhone ou tablet.', 'home'],
  ['Exportação rápida de planilha', 'Baixe todas as fichas ativas em CSV diretamente pela central de ações.', 'catalog'],
  ['Agenda de hoje', 'Veja quantos compromissos estão marcados para hoje e abra a agenda em um toque.', 'agenda'],
  ['Avisos sob demanda', 'Atualize prazos, aniversários e revisitas imediatamente, sem esperar a verificação automática.', 'reminders'],
  ['Tela cheia', 'Oculte as barras do navegador quando houver suporte e ganhe espaço útil em telas pequenas.', 'settings'],
  ['Tema em um toque', 'Alterne entre claro e escuro sem sair da central de ações rápidas.', 'settings'],
  ['Densidade em um toque', 'Troque entre confortável e compacta conforme estiver no celular, tablet ou computador.', 'settings'],
  ['Modais em formato de painel', 'No celular, formulários e detalhes sobem da parte inferior e respeitam a área segura do aparelho.', 'home'],
  ['Abas deslizáveis', 'Abas longas agora rolam horizontalmente sem quebrar ou apertar os nomes.', 'catalog'],
  ['Campos sem zoom acidental', 'Entradas foram dimensionadas para evitar o zoom automático do iPhone ao digitar.', 'add'],
  ['Áreas de toque maiores', 'Botões, campos, menus e ações ganharam alvos confortáveis para uso com os dedos.', 'settings'],
  ['Grades adaptáveis', 'Fichas, fotos, histórias, gráficos, tierlists e ajustes reorganizam-se de verdade em celular e tablet.', 'catalog'],
  ['Respeito à área segura', 'A barra inferior e os painéis evitam o recorte da câmera e o indicador de início do aparelho.', 'home'],
  ['Abas do catálogo consertadas', 'As abas Todas/Favoritos/Arquivadas/Lixeira dobram, grudam no topo e mostram sempre a contagem certa, mesmo com centenas de fichas e fotos.', 'catalog'],
  ['Catálogo que não trava com fotos', 'A lista é carregada em páginas, as imagens só baixam quando aparecem e o rascunho não regrava tudo a cada letra.', 'catalog'],
  ['Fechamento sem bloqueio', 'Fechar ou recarregar a aba não mostra mais aquele aviso eterno quando o catálogo é grande.', 'settings'],
  ['Favoritas mostram tudo', 'A aba Favoritos inclui também fichas arquivadas, como a contagem já prometia.', 'catalog'],
  ['Modelos de cadastro preservados', 'Os modelos salvos voltam a aparecer depois de fechar o aplicativo (eles eram perdidos na leitura dos dados).', 'add'],
  ['Painel com gráficos', 'Pizza por categoria, barras por faixa de nota e idade, média geral e completude em uma tela só.', 'dashboard'],
  ['Radar de atributos', 'Gráfico de aranha com os oito critérios, comparando uma pessoa com a média do catálogo.', 'dashboard'],
  ['Histórico de notas', 'Cada mudança de avaliação é registrada com data e vira uma linha do tempo na ficha.', 'catalog'],
  ['Relatório do mês', 'Quantas pessoas você adicionou, quantas interações registrou e quantas fotos entraram no mês.', 'dashboard'],
  ['Mapa por bairro e cidade', 'Agrupamento por localização com média de cada lugar; um clique filtra o catálogo.', 'dashboard'],
  ['Comparar categorias', 'Escola, igreja, FSY, trabalho: qual origem tem a melhor média, em ranking.', 'dashboard'],
  ['Campeã do mês', 'Destaque automático da ficha mais bem pontuada e da mais vista no mês.', 'dashboard'],
  ['Batalha de categorias', 'Placar direto entre as origens, com contagem de pessoas e nota média.', 'dashboard'],
  ['Raridade', 'Comum, Raro, Épico e Lendário: sugerido pela nota e ajustável na ficha.', 'catalog'],
  ['XP e nível do catálogo', 'Você sobe de nível cadastrando, fotografando, escrevendo e concluindo metas.', 'dashboard'],
  ['Conquistas', '22 medalhas, de “primeira conexão” a “carta lendária”, com aviso ao desbloquear.', 'dashboard'],
  ['Desafios semanais', 'Metas curtas da semana com barra de progresso no painel.', 'dashboard'],
  ['Modo swipe', 'Passe os cartões para a direita (favorita) ou esquerda (passa), com atalhos de seta.', 'discover'],
  ['This or That', 'Duelo entre duas fichas; as vitórias formam um placar automático.', 'discover'],
  ['Radar do duelo', 'Comparação lado a lado com gráfico de aranha das duas pessoas.', 'discover'],
  ['Busca avançada combinada', 'Nota mínima + tag + cabelo + altura + faixa de idade + raridade + pasta, tudo junto.', 'catalog'],
  ['Sugestões de tags', 'Ao cadastrar, o catálogo sugere as etiquetas mais usadas naquela categoria.', 'add'],
  ['Salvar e adicionar outra', 'Cadastro em sequência sem perder o ritmo.', 'add'],
  ['Aniversário e idade automática', 'Informe a data e a idade é calculada; o aviso de aniversário entra na central.', 'add'],
  ['Campos personalizados', 'Crie os campos que quiser (signo, profissão, time) e eles entram na busca.', 'add'],
  ['Anexos por pessoa', 'Links, vídeos, PDFs e áudios guardados na ficha, com validação de endereço.', 'add'],
  ['Favoritar fotos', 'Coração em cada foto da galeria e filtro só de favoritas.', 'gallery'],
  ['Álbuns de fotos', 'Reúna imagens de várias pessoas por evento ou viagem, sem mover arquivos.', 'gallery'],
  ['Detector de duplicatas', 'Acha fotos repetidas pela impressão digital do arquivo e remove as cópias com um clique.', 'gallery'],
  ['Antes e depois', 'Duas fotos com divisor deslizante para comparar na hora.', 'gallery'],
  ['Pastas com subpastas', 'Aninhe pastas, arraste uma sobre a outra, fixe no topo, escolha capa e ordenação.', 'folders'],
  ['Busca de pastas', 'Ache qualquer pasta pelo nome e veja quantos itens ela reúne, incluindo as filhas.', 'folders'],
  ['Notificações de verdade', 'Permissão do navegador, central de avisos com histórico e checagem a cada minuto.', 'settings'],
  ['Radar de prazos', 'Aviso quando falta pouco para um lembrete, compromisso ou meta, e quando faz tempo que você não vê alguém.', 'reminders'],
  ['Lembretes que se repetem', 'Diário, semanal, mensal ou anual: ao concluir, o lembrete já é reagendado.', 'reminders'],
  ['Agenda de encontros', 'Compromissos com local e hora, cronômetro do encontro e histórico de conversas.', 'agenda'],
  ['Meu espaço pessoal', 'Diário com humor, metas, links próprios e um cofre de fotos com PIN separado.', 'myspace'],
  ['Modo pânico', 'Três Esc seguidos (ou Ctrl+Shift+P) escondem tudo na hora.', 'settings'],
  ['Modo disfarce', 'Atalho B desfoca fotos e nomes até você passar o mouse.', 'settings'],
  ['Cores personalizadas', 'Escolha a cor de destaque do tema, aplicada na hora em todo o app.', 'settings'],
  ['Multi-perfis reais', 'Vários catálogos no mesmo dispositivo, cada um com seus dados.', 'settings'],
  ['Capítulos nas fanfics', 'Divida a história em capítulos numerados, reordene e edite cada um.', 'stories'],
  ['Modo leitura focada', 'Tela limpa, texto grande e sem distrações para ler o que você escreveu.', 'stories'],
  ['Estatísticas de texto', 'Palavras, caracteres e tempo de leitura em cada história.', 'stories'],
  ['Exportar histórias', 'Markdown, página web, EPUB de verdade ou impressão em PDF.', 'stories'],
  ['Foto aleatória na abertura', 'Uma capa com uma foto do seu catálogo ao entrar (opcional).', 'settings'],
  ['Atalhos novos', 'D painel, A agenda, M meu espaço, X descobrir, G galeria, B disfarce.', 'guide'],
  ['Busca global ampliada', 'Ctrl+K agora acha notas, histórias, lembretes e fotos, além de pessoas e ações.', 'home'],
  ['Densidade compacta', 'Mais itens por tela em todo o aplicativo, não só no catálogo.', 'settings'],
  ['Limpeza programada da lixeira', 'Defina após quantos dias as fichas da lixeira podem ser limpas, com aviso antes.', 'settings'],
  // Sons, comemorações e brincadeiras
  ['Sons de interface', 'Pop ao favoritar, whoosh no swipe, batida no duelo, arpejo em conquistas e fanfarra ao subir de nível. Tudo gerado na hora, sem baixar nada. Ligado por padrão; desligue ou ajuste o volume em Ajustes → Aparência.', 'settings'],
  ['Silêncio quando precisa', 'Os sons somem sozinhos no modo disfarce, no pânico, na privacidade e quando "reduzir animações" está ligado.', 'settings'],
  ['Confete e cartão de conquista', 'Cada conquista nova chega com chuva de confete e um cartão animado. Pode desligar nos Ajustes.', 'dashboard'],
  ['Comemoração de nível', 'Subiu de nível? Um selo animado sobe no meio da tela com o seu novo título.', 'dashboard'],
  ['Brilho de carta Lendária', 'Fichas com nota 4,8 ou mais ganham borda dourada com brilho passando no catálogo, no swipe e no duelo.', 'catalog'],
  ['Roleta do catálogo', 'Tecla J (ou o botão no Painel) gira uma roleta que passa pelas fichas e para em uma para você rever hoje.', 'dashboard'],
  ['Cinturão da campeã', 'Quem lidera o placar do This or That aparece com cinturão dourado no Painel e na arena do duelo.', 'discover'],
  ['Tons por humor no diário', 'Cada carinha do humor toca uma nota: do tom mais grave no dia difícil ao acorde aberto no dia ótimo.', 'myspace'],
  ['Vibração no celular', 'Passar cartões no swipe dá um toque curto de vibração em aparelhos compatíveis. Opcional.', 'discover'],
  ['Chama da sequência', 'A sequência de dias muda de cor conforme cresce (3, 7 e 30 dias) e mostra quanto falta para o próximo marco.', 'dashboard'],
  ['Código Konami', '↑ ↑ ↓ ↓ ← → ← → B A liga o modo disco: as cores do app giram até você digitar de novo.', 'settings'],
  ['Cronômetro que avisa', 'Durante um encontro, o cronômetro dá um tique a cada 10 minutos e um aviso alegre a cada meia hora.', 'agenda'],
  // Lacunas fechadas
  ['Lixeira que se limpa sozinha', 'O prazo definido em Ajustes → Avisos agora vale de verdade: fichas vencidas saem da lixeira e as fotos ficam guardadas como avulsas.', 'settings'],
  ['Desafios que se concluem', 'Os seis desafios da semana aparecem inteiros, marcam "feito" sozinhos quando a barra enche e rendem +30 XP cada. O de completar fichas agora conta as que ficaram 100% nesta semana.', 'dashboard'],
  ['Fixar no topo', 'Fixe uma ficha pelo menu dela: ela fica sempre em primeiro no catálogo, em qualquer ordenação.', 'catalog'],
  ['Novas ordenações', 'Ordene por fichas menos completas, idade, há mais tempo sem ver ou aniversário mais próximo.', 'catalog'],
  ['Aniversários e revisitas no Painel', 'Um bloco lista quem faz aniversário nos próximos 45 dias e quem você não vê há mais tempo que o limite.', 'dashboard'],
  ['Linha do tempo por pessoa', 'Uma aba nova na ficha reúne cadastro, fotos, interações, notas, encontros, conversas, metas e mudanças de nota em ordem.', 'catalog'],
  ['Exportar tierlist em PNG', 'Salve qualquer tierlist como imagem, com faixas coloridas e retratos, pelo menu Mais.', 'tierlists'],
  ['Agenda para o calendário (.ics)', 'Exporte os compromissos em um arquivo .ics e importe no Google Agenda, Outlook ou iPhone.', 'agenda'],
  // 50+ melhorias: chat, tour, quebra-gelo, campos extras e UX
  ['Simulador de conversa 💬', 'Abra a ficha e escolha "Conversar" para fingir um papo com a pessoa. Escolha o humor (alegre, brincalhona, flertando, tímida, curiosa) e a resposta se adapta ao que você escrever.', 'catalog'],
  ['Quebra-gelos inteligentes', 'O botão "Puxar assunto" gera sugestões montadas pela persona da ficha, em seis grupos (levinho, divertido, profundo, nostalgia, chegar mais perto e picante), com o motivo de cada uma. Um clique copia ou abre o chat.', 'catalog'],
  ['Tour de boas-vindas', 'Na primeira vez que abrir o app, um tour guiado de 5 passos mostra o essencial, com spotlight nos botões mais importantes.', 'home'],
  ['Modo automático dia/noite', 'Ajustes → Tema → Seguir o sistema: o app acompanha o modo claro/escuro do seu sistema operacional automaticamente.', 'settings'],
  ['Campos novos: pronomes, signo, como conheceu e música favorita', 'Quatro novos campos na ficha para guardar detalhes que fazem diferença. Signo tem opções predefinidas.', 'add'],
  ['Sugestão de interesses em comum', 'Nos quebra-gelos, o app mostra outras pessoas do catálogo que compartilham tags ou categoria com ela.', 'catalog'],
  ['Animações mais vivas em todo o app', 'Botões com micro-interações (scale no clique, elevação no hover), cards que pulam, favoritos com pop de coração, toasts com entrada suave e carrossel mais polido.', 'home'],
  ['Status online/digitando no chat simulado', 'O chat mostra "digitando..." com bolinhas animadas e um indicador de online, igual aos apps de mensagem reais.', 'catalog'],
  ['Humor ajustável na conversa simulada', 'Escolha entre 6 humores que mudam o tom das respostas — de respostas mais fofas/tímidas a flertes brincalhões.', 'catalog'],
  ['Histórico de conversa persistente', 'Suas conversas simuladas são salvas no dispositivo — volte quando quiser para "continuar o papo".', 'catalog'],
  ['Brilho de carta lendária melhorado', 'Borda dourada com pulso sutil e um brilho passando mais suave, mais elegante.', 'catalog'],
  ['Indicador de digitação no chat', 'Três pontinhos animados que simulam ela estar realmente respondendo, com delay proporcional ao tamanho da resposta.', 'catalog'],
  ['Aba de conversa um clique da ficha', 'Novo botão "Conversar" proeminente ao lado de Editar e Vi hoje — acesso direto sem procurar.', 'catalog'],
  ['Sugestões de assuntos categorizadas', '5 categorias visuais de quebra-gelo (leve, divertido, profundo, flerte, nostalgia) com emojis e descrições.', 'catalog'],
  ['Copiar a mensagem pronta pro WhatsApp', 'Botão copiar em cada sugestão de papo + botão "Usar" que já abre o chat automaticamente.', 'catalog'],
  ['Som de confete e mais responsivo', 'Animações mais suaves em telas fracas e fallback respeitoso quando não há suporte a áudio.', 'dashboard'],
  // Conversa simulada 2.0
  ['Conversa que lê a ficha inteira', 'O chat monta a personalidade a partir de idade, comportamento, descrição, categoria, tags, signo, música favorita, localização e nível de amizade. Duas fichas diferentes nunca respondem igual.', 'catalog'],
  ['Medidor de química e estágios', 'Cada conversa tem química de 0 a 100 e passa por cinco estágios: conhecendo agora, pegando intimidade, confiante, próxima e especial. O estágio muda o jeito dela falar.', 'catalog'],
  ['O clima sobe sozinho', 'Você não escolhe nada: o chat acompanha a intimidade e vai do papo leve ao flerte quando a relação permite. Se o assunto passar do ponto, ela desconversa em vez de responder.', 'catalog'],
  ['Ela lembra do que você contou', 'Preferências, rotina e planos viram anotações que ela cobra depois ("e aquilo do seu trabalho, como foi?"). A memória pode ser apagada no menu da conversa.', 'catalog'],
  ['Ela nunca repete a mesma frase', 'Cada resposta é sorteada entre centenas de modelos combinados com humor, gírias, emojis, risadas e erros de digitação leves — e as últimas frases usadas saem do sorteio.', 'catalog'],
  ['Humor que muda sozinho', 'Ela também não pede escolha de humor: fica carinhosa quando você desabafa, fechada quando é cobrada e brincalhona quando a conversa solta. O estado aparece no cabeçalho só como leitura.', 'catalog'],
  ['Modo automático de conversa', 'Um toque em "Deixar puxar" e ela manda mensagem sozinha depois de um tempo, retomando assunto do jeito dela.', 'catalog'],
  ['Menu completo da conversa', 'Como ela conversa (cartão da persona), sugestões, mensagem espontânea, copiar ou baixar a conversa em Markdown, limpar memória e reiniciar o papo. Nada de painel de configuração no meio do papo.', 'catalog'],
  ['Modo adulto com trava de idade', 'Em Ajustes → Conversas existe uma opção desligada por padrão, válida apenas para fichas com 18 anos ou mais. Ficha de menor de idade nunca entra em flerte nem em conteúdo adulto, mesmo com a opção ligada.', 'settings'],
  ['Clima picante só para fichas adultas', 'O clima mais quente só acontece com fichas 18+ e o modo adulto ligado, e ainda depende da intimidade construída. O conteúdo é sempre sugestivo e por mensagem, nunca descritivo.', 'catalog'],
  ['Envio de foto na conversa', 'Mande uma foto da galeria no meio do papo e veja a reação dela mudar conforme o tom — e a ficha.', 'catalog'],
  ['Análise da conversa', 'Mensagens trocadas, tamanho médio, perguntas dela, temas mais falados e um aviso honesto quando o papo está desequilibrado.', 'catalog'],
  ['Fotos dela no meio da conversa', 'De vez em quando ela manda uma foto do próprio catálogo, sempre combinando com o tom liberado.', 'catalog'],
  // Caixa de ferramentas: 50 utilidades
  ['Caixa de ferramentas com 50 utilidades', 'A tela Ferramentas (atalho T) reúne 50 funções que trabalham sobre o seu catálogo ou resolvem o dia a dia, com busca e cinco grupos. Nada sai do aparelho.', 'toolbox'],
  ['Grupo Catálogo: conferir e exportar', 'Resumo executivo, verificação de vínculos, mesclar duplicatas, fichas incompletas, CSV sob medida, backup em JSON, auditoria de fotos, estatísticas por grupo, aniversários e linha do tempo da atividade.', 'toolbox'],
  ['Grupo Lote: organizar em massa', 'Padronizar nomes, etiquetar por regra, arquivar quem está sumido, unificar tags parecidas, favoritar por nota, criar pastas por categoria, preencher campos vazios e montar tierlist automática pela nota — sempre com prévia.', 'toolbox'],
  ['Grupo Conversa e social', 'Quebra-gelos por persona, coach de resposta, análise e exportação das conversas, cartão de apresentação da ficha, plano de aproximação em 5 passos, gerador de convite, revisor de mensagem, lembretes de conversa e assuntos que ainda não rolaram.', 'toolbox'],
  ['Grupo Meu espaço e rotina', 'Análise do diário, prompts de escrita guiada, painel de metas, Meu dia em uma tela, modo foco 25+5, cronômetro, metas de conexão e resumo semanal.', 'toolbox'],
  ['Grupo Utilidades do dia a dia', 'Dividir a conta com gorjeta, porcentagem e desconto, conversor de medidas, contas com datas, senha forte, link de WhatsApp com mensagem, formatador de texto, sorteio de pessoas ou de ordem, checklist que vira nota, busca profunda, contador de texto, roteiro de encontro e modelo de ficha.', 'toolbox'],
  ['Ferramentas que mostram antes de mudar', 'Toda ferramenta de escrita exibe o que vai mudar, explica o efeito e pede confirmação. Ctrl+Z desfaz.', 'toolbox'],
];

export const FEATURES = [
  ['Favoritos à mão', 'Uma aba própria e um atalho na ficha para manter as pessoas especiais sempre perto.', 'catalog'],
  ['Arquivo organizado', 'Guarde fichas fora da lista principal e restaure quando quiser.', 'catalog'],
  ['Lixeira recuperável', 'Fotos, notas, histórias, lembretes e posições continuam protegidos para restauração.', 'catalog'],
  ['Organização em lote', 'Aplique tags, categorias, pastas, favoritos e ações em várias fichas de uma vez.', 'catalog'],
  ['Filtros salvos', 'Salve, renomeie e reutilize combinações de busca.', 'catalog'],
  ['Busca global', 'Ctrl+K encontra pessoas, apelidos, contatos, tags, páginas e ações.', 'home'],
  ['Rascunhos recuperáveis', 'Cadastro, edição e fichário rápido preservam o que ainda não foi publicado.', 'drafts'],
  ['Lembretes editáveis', 'Defina data, pessoa, prioridade e detalhes. Conclua ou reagende quando quiser.', 'reminders'],
  ['Modo privacidade', 'Ctrl+Shift+P cobre as informações na hora. O PIN é opcional.', 'settings'],
  ['Categorias do seu jeito', 'Crie e renomeie categorias e subcategorias preservando vínculos.', 'taxonomy'],
  ['Localizações reutilizáveis', 'Cadastre bairros e cidades para preencher fichas com mais rapidez.', 'taxonomy'],
  ['Tags com identidade', 'Crie, renomeie e escolha cores para tags próprias.', 'taxonomy'],
  ['Nomes e apelidos', 'Edite nomes de pessoas, perfil, usuário de acesso e tierlists.', 'catalog'],
  ['Possíveis duplicatas', 'Revise coincidências de nome, telefone ou contato sem mesclagens automáticas.', 'duplicates'],
  ['Cópias independentes', 'Duplique fichas, quadros ou tierlists sem alterar a original.', 'tierlists'],
  ['Exportação CSV', 'Exporte resultados filtrados ou apenas as fichas selecionadas.', 'catalog'],
  ['Desfazer e refazer', 'Recupere até 20 alterações nesta sessão.', 'home'],
  ['Pontos de restauração', 'Guarde até cinco versões locais e baixe cópias externas.', 'settings'],
  ['Salvamento transparente', 'IndexedDB, cópia pendente e indicador real de gravação.', 'settings'],
  ['Upload em lote', 'Arraste várias imagens, valide e otimize antes de guardar.', 'gallery'],
  ['Galeria por pastas', 'Organize fotos por pessoa, tipo, data, pasta e seleção múltipla.', 'gallery'],
  ['Fotos em tela cheia', 'Amplie, navegue com setas, vincule e classifique sem sair da galeria.', 'gallery'],
  ['Pastas mistas', 'Reúna pessoas, fotos, notas e histórias sem duplicar os itens.', 'folders'],
  ['Notas gerais', 'Guarde ideias, referências e lembretes fora das fichas.', 'notes'],
  ['Quadro de investigação', 'Conecte pistas, fichas, notas e pastas em etapas pessoais.', 'board'],
  ['Nível de amizade', 'Registre proximidade sem mexer na nota geral.', 'add'],
  ['Estilo e características', 'Mais opções de cabelo, tipo de corpo e estilo de roupa.', 'add'],
  ['Tags de aparência adultas', 'Use classificações pessoais apenas em fichas verificadas como adultas.', 'add'],
  ['Fichas a completar', 'Veja o progresso de cada ficha e filtre as que precisam de detalhes.', 'catalog'],
  ['Tierlists reordenáveis', 'Mova pessoas, reordene faixas e personalize cores e nomes.', 'tierlists'],
  ['Impressão organizada', 'Imprima fichas e rankings, ou salve em PDF pelo navegador.', 'ranking'],
  ['Acessibilidade de leitura', 'Aumente textos ou reduza animações nas preferências.', 'settings'],
] as const;