import { useMemo, useState } from 'react';
import { ArrowRight, Archive, Bell, BookOpen, Bookmark, CalendarDays, ClipboardList, EyeOff, FileText, Folder, Gauge, Heart, Image as ImageIcon, KeyRound, Layers, Plus, ScanEye, Search, Settings2, Shapes, Shuffle, Sparkles, Trash2, Trophy, UserCircle2, Users } from 'lucide-react';
import { useCatalog } from '../context';
import { isActive, locationLabel, matchesSearch, normalizeText } from '../store';
import { Avatar, Modal } from './ui';

export default function CommandPalette() {
  const ctx = useCatalog(), { data } = ctx;
  const [query, setQuery] = useState(''); const [index, setIndex] = useState(0); const [includeArchived, setIncludeArchived] = useState(false);
  const people = useMemo(() => data.people.filter(p => !p.deletedAt && (includeArchived || !p.archivedAt) && matchesSearch(p, query, data)).sort((a, b) => Number(!!b.favorite) - Number(!!a.favorite)).slice(0, 8), [data, query, includeArchived]);
  const actions = [{ title: 'Novo fichário rápido', icon: Plus, hint: 'N', run: () => ctx.setQuickOpen(true) }, { title: 'Catálogo completo', icon: Users, hint: '2', run: () => ctx.navigate('catalog', 'active') }, { title: 'Meus favoritos', icon: Heart, hint: '', run: () => ctx.navigate('catalog', 'favorites') }, { title: 'Fichas arquivadas', icon: Archive, hint: '', run: () => ctx.navigate('catalog', 'archived') }, { title: 'Lixeira recuperável', icon: Trash2, hint: '', run: () => ctx.navigate('catalog', 'trash') }, { title: 'Minhas tierlists', icon: Layers, hint: '4', run: () => ctx.navigate('tierlists') }, { title: 'Ranking', icon: Trophy, hint: '3', run: () => ctx.navigate('ranking') }, { title: 'Categorias e localizações', icon: Shapes, hint: '', run: () => ctx.navigate('taxonomy') }, { title: 'Lembretes', icon: Bell, hint: '', run: () => ctx.navigate('reminders') }, { title: 'Notas gerais', icon: FileText, hint: '', run: () => ctx.navigate('notes') }, { title: 'Pastas', icon: Folder, hint: '', run: () => ctx.navigate('folders') }, { title: 'Quadro de investigação', icon: ClipboardList, hint: '', run: () => ctx.navigate('board') }, { title: 'Rascunhos recuperáveis', icon: FileText, hint: '', run: () => ctx.navigate('drafts') }, { title: 'Comparar pessoas', icon: Users, hint: 'C', run: () => ctx.setCompareIds([]) }, { title: 'Roleta do catálogo', icon: Shuffle, hint: 'J', run: () => ctx.setRouletteOpen(true) }, { title: 'Surpresa: pessoa aleatória', icon: Shuffle, hint: '', run: () => { const people = data.people.filter(isActive); if (people.length) ctx.openPerson(people[Math.floor(Math.random() * people.length)]); } }, { title: 'Painel com gráficos', icon: Gauge, hint: 'D', run: () => ctx.navigate('dashboard') }, { title: 'Meu espaço pessoal', icon: UserCircle2, hint: 'M', run: () => ctx.navigate('myspace') }, { title: 'Agenda e encontros', icon: CalendarDays, hint: 'A', run: () => ctx.navigate('agenda') }, { title: 'Descobrir (swipe e duelos)', icon: Sparkles, hint: 'X', run: () => ctx.navigate('discover') }, { title: 'Galeria de fotos', icon: ImageIcon, hint: 'G', run: () => ctx.navigate('gallery') }, { title: 'Cofre de fotos', icon: KeyRound, hint: '', run: () => ctx.navigate('myspace') }, { title: 'Central de avisos', icon: Bell, hint: '', run: () => ctx.setNotificationsOpen(true) }, { title: ctx.blur ? 'Desativar modo disfarce' : 'Ativar modo disfarce', icon: ScanEye, hint: 'B', run: () => ctx.setBlur(!ctx.blur) }, { title: 'Ativar privacidade agora', icon: EyeOff, hint: 'Ctrl Shift P', run: () => ctx.setPrivacy(true) }, { title: 'Perfil e ajustes', icon: Settings2, hint: '8', run: () => ctx.navigate('settings') }].filter(a => !query || normalizeText(a.title).includes(normalizeText(query)));
  const saved = data.savedFilters.filter(f => !query || normalizeText(f.name).includes(normalizeText(query))).slice(0, 4);
  // A busca global também atravessa notas, histórias, lembretes e fotos.
  const term = normalizeText(query);
  const notes = query ? data.generalNotes.filter(note => normalizeText(`${note.title} ${note.content}`).includes(term)).slice(0, 3) : [];
  const stories = query ? data.stories.filter(story => normalizeText(`${story.titulo} ${story.conteudo}`).includes(term)).slice(0, 3) : [];
  const reminders = query ? data.reminders.filter(reminder => normalizeText(`${reminder.titulo} ${reminder.descricao || ''}`).includes(term)).slice(0, 3) : [];
  const photos = query ? [...data.orphanPhotos, ...data.people.flatMap(person => person.fotos)].filter(photo => normalizeText(`${photo.name || ''} ${photo.description || ''}`).includes(term)).slice(0, 3) : [];
  const count = people.length + saved.length + actions.length;
  const run = (i: number) => { if (i < people.length) ctx.openPerson(people[i]); else if (i < people.length + saved.length) { ctx.setFilter(saved[i - people.length].filter); ctx.navigate('catalog'); } else actions[i - people.length - saved.length]?.run(); ctx.setCommandOpen(false); };
  return <Modal title="Encontre sua próxima conexão" onClose={() => ctx.setCommandOpen(false)} className="command-modal"><div className="command-search"><Search size={21} /><input value={query} onChange={e => { setQuery(e.target.value); setIndex(0); }} placeholder="Pessoas, contato, tags, páginas ou ações..." aria-label="Busca global" onKeyDown={e => { if (e.key === 'ArrowDown') { e.preventDefault(); setIndex(i => Math.min(Math.max(0, count - 1), i + 1)); } if (e.key === 'ArrowUp') { e.preventDefault(); setIndex(i => Math.max(0, i - 1)); } if (e.key === 'Enter' && count > 0) { e.preventDefault(); run(index); } }} /><kbd>Ctrl K</kbd></div><div className="command-filter"><label><input type="checkbox" checked={includeArchived} onChange={e => setIncludeArchived(e.target.checked)} />Incluir fichas arquivadas</label><span>{people.length} pessoas</span></div><div className="command-results">{!!people.length && <p className="eyebrow">Pessoas</p>}{people.map((p, i) => <button key={p.id} className={i === index ? 'active' : ''} onMouseEnter={() => setIndex(i)} onClick={() => run(i)}><Avatar person={p} size={40} /><span><strong>{p.nome}{p.favorite && <Heart size={12} fill="currentColor" />}</strong><small>{p.apelido ? `${p.apelido} · ` : ''}{locationLabel(p, data)}{p.archivedAt ? ' · Arquivada' : ''}</small></span><ArrowRight size={15} /></button>)}{!!saved.length && <p className="eyebrow">Buscas salvas</p>}{saved.map((s, i) => <button key={s.id} className={i + people.length === index ? 'active' : ''} onMouseEnter={() => setIndex(i + people.length)} onClick={() => run(i + people.length)}><Bookmark size={17} /><span>{s.name}</span><ArrowRight size={15} /></button>)}{!!notes.length && <p className="eyebrow">Notas</p>}{notes.map(note => <button key={note.id} onClick={() => { ctx.navigate('notes'); ctx.setCommandOpen(false); }}><FileText size={17} /><span><strong>{note.title}</strong><small>{note.content.slice(0, 60)}</small></span><ArrowRight size={15} /></button>)}
      {!!stories.length && <p className="eyebrow">Histórias</p>}{stories.map(story => <button key={story.id} onClick={() => { ctx.navigate('stories'); ctx.setCommandOpen(false); }}><BookOpen size={17} /><span><strong>{story.titulo}</strong><small>{story.conteudo.slice(0, 60)}</small></span><ArrowRight size={15} /></button>)}
      {!!reminders.length && <p className="eyebrow">Lembretes</p>}{reminders.map(reminder => <button key={reminder.id} onClick={() => { ctx.navigate('reminders'); ctx.setCommandOpen(false); }}><Bell size={17} /><span><strong>{reminder.titulo}</strong><small>{reminder.concluido ? 'Concluído' : 'Pendente'}</small></span><ArrowRight size={15} /></button>)}
      {!!photos.length && <p className="eyebrow">Fotos</p>}{photos.map(photo => <button key={photo.id} onClick={() => { ctx.navigate('gallery'); ctx.setCommandOpen(false); }}><ImageIcon size={17} /><span><strong>{photo.name || 'Foto'}</strong><small>{data.people.find(person => person.fotos.some(file => file.id === photo.id))?.nome || 'Não vinculada'}</small></span><ArrowRight size={15} /></button>)}
      {!!actions.length && <p className="eyebrow">Ações rápidas</p>}{actions.map((a, i) => <button key={a.title} className={i + people.length + saved.length === index ? 'active' : ''} onMouseEnter={() => setIndex(i + people.length + saved.length)} onClick={() => run(i + people.length + saved.length)}><a.icon size={17} /><span>{a.title}</span>{a.hint && <kbd>{a.hint}</kbd>}</button>)}{!count && <p className="command-empty">Nada encontrado. Tente outro nome, contato ou categoria.</p>}</div><div className="command-footer"><span>Setas para navegar</span><span>Enter para abrir</span><span>Esc para fechar</span></div></Modal>;
}