import { useMemo, useState } from 'react';
import { Check, Edit3, FileText, Folder, FolderOpen, Heart, Image, Link2, Plus, Sparkles, Trash2, Users } from 'lucide-react';
import type { Folder as FolderType } from '../types';
import { useCatalog } from '../context';
import { allFolderItems, generateId, getAllPhotos, PALETTE } from '../store';
import { Avatar, Button, CheckBox, Confirm, EmptyState, Field, IconButton, Modal, PageTitle, PhotoView } from './ui';

const ICONS = { folder: Folder, image: Image, note: FileText, bookmark: Sparkles, heart: Heart, sparkles: Sparkles };
const ICON_LABELS: Record<keyof typeof ICONS, string> = { folder: 'Pasta', image: 'Imagem', note: 'Nota', bookmark: 'Marcador', heart: 'Coração', sparkles: 'Brilho' };
export default function Folders() {
  const ctx = useCatalog(), { data } = ctx; const [openId, setOpenId] = useState<string | null>(null); const [editing, setEditing] = useState<FolderType | null>(null); const [deleting, setDeleting] = useState<string | null>(null);
  const open = data.folders.find(f => f.id === openId); const allPhotos = useMemo(() => getAllPhotos(data), [data]);
  const create = () => setEditing({ id: generateId(), name: '', color: PALETTE[0], icon: 'folder', description: '', personIds: [], photoIds: [], noteIds: [], storyIds: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
  const save = () => { if (!editing?.name.trim()) { ctx.notify('Dê um nome à pasta.', true); return; } const folder = { ...editing, name: editing.name.trim(), updatedAt: new Date().toISOString() }; ctx.commit(d => ({ ...d, folders: d.folders.some(f => f.id === folder.id) ? d.folders.map(f => f.id === folder.id ? folder : f) : [...d.folders, folder], generalNotes: d.generalNotes.map(n => folder.noteIds.includes(n.id) ? { ...n, folderId: folder.id } : n.folderId === folder.id ? { ...n, folderId: null } : n) }), 'Pasta salva.'); setEditing(null); };
  const remove = () => { if (!deleting) return; ctx.commit(d => ({ ...d, folders: d.folders.filter(f => f.id !== deleting), generalNotes: d.generalNotes.map(n => n.folderId === deleting ? { ...n, folderId: null } : n), investigationBoards: d.investigationBoards.map(b => ({ ...b, cards: b.cards.map(c => c.folderId === deleting ? { ...c, folderId: null } : c) })) }), 'Pasta removida. Seus itens continuam no catálogo.'); if (openId === deleting) setOpenId(null); };
  const FolderIcon = open ? ICONS[open.icon as keyof typeof ICONS] || Folder : Folder;
  if (open) { const items = allFolderItems(data, open.id); return <div className="folders-page"><button className="back-link" onClick={() => setOpenId(null)}><FolderOpen size={16} />Todas as pastas</button><PageTitle eyebrow="Tudo reunido em um lugar" title={open.name} description={open.description || 'Uma pasta pessoal do seu catálogo.'}><Button onClick={() => setEditing(structuredClone(open))}><Edit3 size={16} />Editar pasta</Button></PageTitle><div className="folder-detail-hero" style={{ '--folder': open.color } as React.CSSProperties}><FolderIcon size={55} /><div><strong>{items.people.length + items.photos.length + items.notes.length + items.stories.length}</strong><span>itens reunidos</span></div><p>{open.description || 'Adicione pessoas, fotos, notas ou histórias nesta pasta para vê-las aqui.'}</p></div><div className="folder-detail-grid"><section><h2><Users size={17} />Pessoas</h2><div className="folder-people">{items.people.map(p => <button key={p.id} onClick={() => ctx.openPerson(p)}><Avatar person={p} size={46} /><span>{p.nome}<small>{p.apelido || 'Ver ficha'}</small></span></button>)}{!items.people.length && <p className="form-help">Nenhuma pessoa nesta pasta ainda.</p>}</div></section><section><h2><Image size={17} />Fotos</h2><div className="folder-photos">{items.photos.map(photo => <button key={photo.id} onClick={() => ctx.navigate('gallery')}><PhotoView src={photo.url} alt={photo.name} /></button>)}{!items.photos.length && <p className="form-help">Nenhuma foto reunida.</p>}</div></section><section><h2><FileText size={17} />Notas</h2>{items.notes.map(note => <button className="folder-note" key={note.id} onClick={() => ctx.navigate('notes')}><strong>{note.title}</strong><p>{note.content}</p></button>)}{!items.notes.length && <p className="form-help">Nenhuma nota reunida.</p>}</section></div>{items.stories.length > 0 && <section className="folder-stories"><h2><Sparkles size={17} />Histórias</h2>{items.stories.map(story => <button key={story.id} onClick={() => ctx.navigate('stories')}><strong>{story.titulo}</strong><span>{story.tipo}</span></button>)}</section>}{editing && <FolderEditor folder={editing} setFolder={setEditing} allPhotos={allPhotos} onSave={save} onClose={() => setEditing(null)} />}{deleting && <Confirm title="Excluir esta pasta?" description="Pessoas, fotos, notas e histórias continuarão intactas no catálogo. Apenas o agrupamento será removido." danger confirmLabel="Excluir pasta" onClose={() => setDeleting(null)} onConfirm={remove} />}</div>; }
  return <div className="folders-page"><PageTitle eyebrow="Agrupe do seu jeito" title="Pastas" description="Reúna pessoas, fotos, anotações e histórias sem mudar os dados originais."><Button variant="primary" onClick={create}><Plus size={17} />Nova pasta</Button></PageTitle><div className="folders-grid">{data.folders.map(folder => { const Icon = ICONS[folder.icon as keyof typeof ICONS] || Folder; const items = allFolderItems(data, folder.id); return <article key={folder.id} className="folder-card" style={{ '--folder': folder.color } as React.CSSProperties}><button onClick={() => setOpenId(folder.id)}><span className="folder-card-icon"><Icon size={31} /></span><h2>{folder.name}</h2><p>{folder.description || 'Pasta pessoal'}</p><div><span><Users size={13} />{items.people.length}</span><span><Image size={13} />{items.photos.length}</span><span><FileText size={13} />{items.notes.length}</span></div></button><footer><button className="text-action" onClick={() => setOpenId(folder.id)}>Abrir pasta<Link2 size={14} /></button><span><IconButton label="Editar pasta" onClick={() => setEditing(structuredClone(folder))}><Edit3 size={15} /></IconButton><IconButton label="Excluir pasta" onClick={() => setDeleting(folder.id)}><Trash2 size={15} /></IconButton></span></footer></article>; })}</div>{!data.folders.length && <EmptyState icon={Folder} title="Uma pasta para cada momento" description="Agrupe pessoas, fotos, notas e histórias sem criar cópias ou alterar os vínculos originais." action="Criar primeira pasta" onAction={create} />}{editing && <FolderEditor folder={editing} setFolder={setEditing} allPhotos={allPhotos} onSave={save} onClose={() => setEditing(null)} />}{deleting && <Confirm title="Excluir esta pasta?" description="Pessoas, fotos, notas e histórias continuarão intactas no catálogo. Apenas o agrupamento será removido." danger confirmLabel="Excluir pasta" onClose={() => setDeleting(null)} onConfirm={remove} />}</div>;
}
function FolderEditor({ folder, setFolder, allPhotos, onSave, onClose }: { folder: FolderType; setFolder: (f: FolderType) => void; allPhotos: ReturnType<typeof getAllPhotos>; onSave: () => void; onClose: () => void }) {
  const { data } = useCatalog();
  const toggle = (key: 'personIds' | 'photoIds' | 'noteIds' | 'storyIds', id: string) => setFolder({ ...folder, [key]: folder[key].includes(id) ? folder[key].filter(x => x !== id) : [...folder[key], id] });
  return <Modal title={data.folders.some(f => f.id === folder.id) ? 'Editar pasta' : 'Nova pasta'} description="Uma pasta apenas reúne referências; ela não duplica seus itens." onClose={onClose} wide footer={<><Button onClick={onClose}>Cancelar</Button><Button variant="primary" disabled={!folder.name.trim()} onClick={onSave}><Check size={16} />Salvar pasta</Button></>}><div className="form-grid"><Field label="Nome"><input value={folder.name} onChange={e => setFolder({ ...folder, name: e.target.value })} placeholder="Ex.: Viagem de julho" maxLength={100} /></Field><Field label="Ícone"><select value={folder.icon} onChange={e => setFolder({ ...folder, icon: e.target.value })}>{(Object.keys(ICONS) as (keyof typeof ICONS)[]).map(icon => <option key={icon} value={icon}>{ICON_LABELS[icon]}</option>)}</select></Field></div><Field label="Descrição"><textarea rows={2} value={folder.description} onChange={e => setFolder({ ...folder, description: e.target.value })} placeholder="O que esta pasta reúne?" /></Field><Field label="Cor"><div className="color-picker">{PALETTE.map(color => <button key={color} style={{ background: color }} aria-label={`Cor ${color}`} aria-pressed={folder.color === color} onClick={() => setFolder({ ...folder, color })}>{folder.color === color && <Check size={14} />}</button>)}<input type="color" value={folder.color} onChange={e => setFolder({ ...folder, color: e.target.value })} /></div></Field><div className="folder-editor-pickers"><Picker title="Pessoas" values={folder.personIds} items={data.people.filter(p => !p.deletedAt).map(p => ({ id: p.id, label: p.nome }))} toggle={id => toggle('personIds', id)} /><Picker title="Fotos" values={folder.photoIds} items={allPhotos.map(p => ({ id: p.id, label: `${data.people.find(person => person.id === p.personId)?.nome || 'Não vinculada'} · ${p.name || 'Foto'}` }))} toggle={id => toggle('photoIds', id)} /><Picker title="Notas" values={folder.noteIds} items={data.generalNotes.map(n => ({ id: n.id, label: n.title }))} toggle={id => toggle('noteIds', id)} /><Picker title="Histórias" values={folder.storyIds} items={data.stories.map(s => ({ id: s.id, label: s.titulo }))} toggle={id => toggle('storyIds', id)} /></div></Modal>;
}
function Picker({ title, values, items, toggle }: { title: string; values: string[]; items: { id: string; label: string }[]; toggle: (id: string) => void }) { return <section><h3>{title}<small>{values.length}</small></h3><div>{items.map(item => <CheckBox key={item.id} checked={values.includes(item.id)} onChange={() => toggle(item.id)} label={item.label} />)}{!items.length && <p className="form-help">Nenhum item disponível.</p>}</div></section>; }