import { useRef, useState } from 'react';
import { Camera, Check, FileText, ImagePlus, Plus, Save, Star, Trash2, Upload, User } from 'lucide-react';
import type { Person, Photo } from '../types';
import { ADULT_APPEARANCE_TAGS, ALTURA_OPTIONS, CABELO_COR_OPTIONS, CABELO_TIPO_OPTIONS, ESTILO_ROUPA_OPTIONS, FRIENDSHIP_LEVELS, PELE_OPTIONS, QI_OPTIONS, TIPO_CORPO_OPTIONS } from '../types';
import { useCatalog } from '../context';
import { calculateOverallRating, findDuplicates, formatDate, formatNumber, friendshipLabel, generateId, getAllTagNames, isAdult, normalizePhotos, PHOTO_LABELS, readImage, RATING_FIELDS, today } from '../store';
import { Button, CheckBox, EmptyState, Field, IconButton, Modal, PhotoView } from './ui';
import StarRating from './StarRating';

const OPTION_LABELS: Record<string, string> = { medio: 'Médio', trancado: 'Trançado', indigena: 'Indígena', 'abaixo da media': 'Abaixo da média', 'acima da media': 'Acima da média', genio: 'Gênio' };
function Options({ options, value }: { options: string[]; value: string }) { return <><option value="">Não informado</option>{value && !options.includes(value) && <option value={value}>{value}</option>}{options.map(s => <option key={s} value={s}>{OPTION_LABELS[s] || s.charAt(0).toUpperCase() + s.slice(1)}</option>)}</>; }

export function PhotoUploader({ onFiles, busy, large = false }: { onFiles: (files: File[]) => void; busy?: boolean; large?: boolean }) {
  const input = useRef<HTMLInputElement>(null); const [drag, setDrag] = useState(false);
  return <div className={`upload-zone ${drag ? 'drag-over' : ''} ${large ? 'upload-large' : ''}`} onDragOver={e => { e.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); if (!busy) onFiles(Array.from(e.dataTransfer.files)); }}><input ref={input} type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" className="sr-only" aria-label="Selecionar imagens" onChange={e => { onFiles(Array.from(e.target.files || [])); e.target.value = ''; }} /><Upload size={26} strokeWidth={1.5} /><strong>{busy ? 'Preparando imagens...' : 'Arraste suas fotos até aqui'}</strong><span>JPG, PNG, WebP ou GIF, até 20 MB por imagem.</span><Button onClick={() => input.current?.click()} disabled={busy}><ImagePlus size={17} />{busy ? 'Aguarde' : 'Escolher imagens'}</Button></div>;
}

export default function PersonEditor({ person, update, quick = false, onSave, onCancel, dirty, recovered, onDiscard, submitLabel = 'Salvar ficha' }: {
  person: Person; update: (p: Person | ((p: Person) => Person)) => void; quick?: boolean; onSave: () => void; onCancel: () => void; dirty: boolean; recovered: boolean; onDiscard: () => void; submitLabel?: string;
}) {
  const { data, notify, commit, status, demo } = useCatalog();
  const [tab, setTab] = useState('info'); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState(false);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null); const [newTag, setNewTag] = useState('');
  const category = data.categories.find(c => c.value === person.localizacaoOnde);
  const adult = isAdult(person);
  const selectableTags = getAllTagNames(data).filter(tag => adult || !ADULT_APPEARANCE_TAGS.includes(tag));
  const field = <K extends keyof Person>(key: K, value: Person[K]) => update(p => ({ ...p, [key]: value }));
  const setRating = (key: keyof Person['rating'], value: number | string) => update(p => ({ ...p, rating: { ...p.rating, ...(key === 'mode' && value === 'manual' ? { overall: calculateOverallRating(p.rating) } : {}), [key]: value } }));
  const upload = async (files: File[]) => {
    setBusy(true);
    try {
      const images = await Promise.all(files.map(async file => ({ id: generateId(), url: await readImage(file), name: file.name, personId: person.id, isMain: false, type: 'normal' as const, createdAt: new Date().toISOString() })));
      update(p => ({ ...p, fotos: normalizePhotos([...p.fotos, ...images], p.id) }));
      notify(`${images.length} imagem(ns) preparada(s).`);
    } catch (error) { notify((error as Error).message, true); } finally { setBusy(false); }
  };
  const addTag = () => { const name = newTag.trim().toLocaleLowerCase('pt-BR'); if (!name) return; if (!adult && ADULT_APPEARANCE_TAGS.includes(name)) { notify('Essa tag de aparência só pode ser usada em fichas adultas.', true); return; } if (!getAllTagNames(data).includes(name)) commit(d => ({ ...d, settings: { ...d.settings, customTags: [...d.settings.customTags, { nome: name, cor: '#c786ec' }] } }), 'Tag criada.'); update(p => ({ ...p, tags: [...new Set([...p.tags, name])] })); setNewTag(''); };
  const potential = findDuplicates({ ...data, people: [...data.people.filter(p => p.id !== person.id), person] }).filter(pair => pair.a.id === person.id || pair.b.id === person.id);
  const valid = !!person.nome.trim() && (quick || !!person.descricao.trim()) && (person.idade === null || Number.isInteger(person.idade) && person.idade >= 0 && person.idade <= 120);
  const draftLabel = demo ? 'Rascunho temporário da demonstração.' : status === 'saved' ? 'Rascunho salvo neste dispositivo.' : status === 'error' ? 'A gravação falhou. Confira o aviso de salvamento.' : 'Salvando seu rascunho...';
  return <form className={`person-editor ${quick ? 'quick-editor' : ''}`} onSubmit={e => { e.preventDefault(); if (valid && !busy) onSave(); }}>
    {(dirty || recovered) && <div className="draft-notice"><FileText size={17} /><span>{recovered ? 'Rascunho recuperado. Continue de onde parou.' : draftLabel}</span><button type="button" className="text-action muted" onClick={onDiscard}>Descartar</button></div>}
    {!quick && <div className="editor-tabs"><button type="button" className={tab === 'info' ? 'active' : ''} onClick={() => setTab('info')}><User size={17} />Informações</button><button type="button" className={tab === 'ratings' ? 'active' : ''} onClick={() => setTab('ratings')}><Star size={17} />Avaliações</button><button type="button" className={tab === 'notes' ? 'active' : ''} onClick={() => setTab('notes')}><FileText size={17} />Notas <small>{person.notas.length}</small></button><button type="button" className={tab === 'photos' ? 'active' : ''} onClick={() => setTab('photos')}><Camera size={17} />Fotos <small>{person.fotos.length}</small></button></div>}
    {preview ? <div className="editor-preview"><PhotoView person={person} /><div><p className="eyebrow">Prévia da ficha</p><h2>{person.nome || 'Nome da pessoa'}</h2><StarRating value={calculateOverallRating(person.rating)} readonly /><p>{person.descricao || 'Você poderá completar a descrição depois.'}</p><span className="muted">{category?.label || 'Sem categoria'}</span></div></div> : <>
      {(tab === 'info' || quick) && <div className="editor-info">
        {quick && <div className="quick-photo"><PhotoView person={person} /><Button onClick={() => setTab(tab === 'photos' ? 'info' : 'photos')}><Camera size={16} />{person.fotos.length ? 'Alterar foto' : 'Adicionar foto'}</Button></div>}
        <div className="form-grid"><Field label="Nome *"><input value={person.nome} onChange={e => field('nome', e.target.value)} placeholder="Como a pessoa se chama?" required maxLength={100} /></Field><Field label="Apelido"><input value={person.apelido || ''} onChange={e => field('apelido', e.target.value)} placeholder="Opcional" maxLength={80} /></Field>
          <Field label="Categoria"><select value={person.localizacaoOnde} onChange={e => update(p => ({ ...p, localizacaoOnde: e.target.value, localizacaoSub: '' }))}><option value="">Escolher categoria</option>{data.categories.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}</select></Field>
          <Field label="Subcategoria"><select value={person.localizacaoSub} disabled={!category?.subs?.length} onChange={e => field('localizacaoSub', e.target.value)}><option value="">{category?.subs?.length ? 'Escolher subcategoria' : 'Sem subcategorias'}</option>{category?.subs?.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}</select></Field>
          <Field label={quick ? 'Descrição (opcional)' : 'Descrição *'} className="span-2"><textarea value={person.descricao} onChange={e => field('descricao', e.target.value)} rows={quick ? 2 : 3} placeholder="O que você gostaria de lembrar sobre essa pessoa?" required={!quick} /></Field>
          {!quick && <><Field label="Idade"><input type="number" min={0} max={120} value={person.idade ?? ''} onChange={e => field('idade', e.target.value === '' ? null : Number(e.target.value))} placeholder="Não informada" /></Field><Field label="Altura"><select value={person.altura} onChange={e => field('altura', e.target.value)}><Options options={ALTURA_OPTIONS} value={person.altura} /></select></Field><Field label="Redes sociais / WhatsApp"><input value={person.redesSociais} onChange={e => field('redesSociais', e.target.value)} placeholder="Contato ou @usuário" /></Field><Field label="Onde mora / localização"><input list={`locations-${person.id}`} value={person.localizacaoMora} onChange={e => field('localizacaoMora', e.target.value)} placeholder="Bairro, cidade ou local" /><datalist id={`locations-${person.id}`}>{data.locations.map(s => <option key={s} value={s} />)}</datalist></Field><Field label="Último visto / interação"><input type="date" value={person.ultimoVisto || ''} max={today()} onChange={e => field('ultimoVisto', e.target.value || null)} /></Field><Field label="Q.I. (anotação pessoal)"><select value={person.qi} onChange={e => field('qi', e.target.value)}><Options options={QI_OPTIONS} value={person.qi} /></select></Field></>}
        </div>
        <div className="friendship-level">
          <div><h3>Nível de amizade</h3><p>Este dado é independente da avaliação e nunca altera a nota geral.</p></div>
          <div className="friendship-control"><input type="range" min="0" max="5" step="1" value={person.friendshipLevel || 0} aria-label="Nível de amizade" onChange={e => field('friendshipLevel', Number(e.target.value))} /><div>{FRIENDSHIP_LEVELS.map(level => <button type="button" key={level.value} className={(person.friendshipLevel || 0) === level.value ? 'active' : ''} onClick={() => field('friendshipLevel', level.value)} aria-label={level.label}>{level.value}</button>)}</div><strong>{friendshipLabel(person.friendshipLevel)}</strong></div>
        </div>
        {potential.length > 0 && <div className="inline-notice warning"><FileText size={17} />{potential.length} possível(is) duplicata(s) por nome ou contato. Confira em Organizar antes de salvar.</div>}
        <div className="form-section"><h3>Tags</h3><div className="tag-picker">{selectableTags.map(tag => <button type="button" key={tag} aria-pressed={person.tags.includes(tag)} className={person.tags.includes(tag) ? 'selected' : ''} onClick={() => field('tags', person.tags.includes(tag) ? person.tags.filter(t => t !== tag) : [...person.tags, tag])}>{person.tags.includes(tag) && <Check size={12} />}{tag}</button>)}</div>{!adult && <p className="form-help">As etiquetas de aparência (gostosa, bonita, bonitinha, cavala, gata, gatinha, dá pra ir) continuam salvas, mas só aparecem na paleta quando a ficha informa 18 anos ou mais. Todas as outras etiquetas ficam sempre disponíveis.</p>}<div className="inline-create"><input value={newTag} onChange={e => setNewTag(e.target.value)} placeholder="Nova tag" aria-label="Nome da nova tag" onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addTag(); } }} /><Button onClick={addTag} disabled={!newTag.trim()}><Plus size={15} />Criar tag</Button></div></div>
        {!quick && <><div className="form-section"><h3>Aparência e características</h3><div className="form-grid"><Field label="Tipo de cabelo"><select value={person.cabeloTipo} onChange={e => field('cabeloTipo', e.target.value)}><Options options={CABELO_TIPO_OPTIONS} value={person.cabeloTipo} /></select></Field><Field label="Cor do cabelo"><select value={person.cabeloCor} onChange={e => field('cabeloCor', e.target.value)}><Options options={CABELO_COR_OPTIONS} value={person.cabeloCor} /></select></Field>{person.cabeloCor === 'colorido' && <Field label="Qual cor?"><input value={person.cabeloCorCustom} onChange={e => field('cabeloCorCustom', e.target.value)} /></Field>}<Field label="Tom de pele"><select value={person.pele} onChange={e => field('pele', e.target.value)}><Options options={PELE_OPTIONS} value={person.pele} /></select></Field>{person.pele === 'personalizado' && <Field label="Tom personalizado"><input value={person.peleCustom} onChange={e => field('peleCustom', e.target.value)} /></Field>}<Field label="Tipo de corpo"><select value={person.tipoCorpo || ''} onChange={e => field('tipoCorpo', e.target.value)}><Options options={TIPO_CORPO_OPTIONS} value={person.tipoCorpo || ''} /></select></Field><Field label="Estilo de roupa"><select value={person.estiloRoupa || ''} onChange={e => field('estiloRoupa', e.target.value)}><Options options={ESTILO_ROUPA_OPTIONS} value={person.estiloRoupa || ''} /></select></Field><Field label="Descrição corporal" className="span-2"><textarea rows={3} value={person.descricaoCorporal} onChange={e => field('descricaoCorporal', e.target.value)} placeholder="Características, tatuagens, piercings ou outros detalhes." /></Field><Field label="Observações gerais" className="span-2"><textarea rows={3} value={person.observacoesGerais || ''} onChange={e => field('observacoesGerais', e.target.value)} placeholder="Anotações gerais que não entram em nenhuma seção específica." /></Field><Field label="Comportamento" className="span-2"><textarea rows={3} value={person.comportamento} onChange={e => field('comportamento', e.target.value)} placeholder="Anotações sobre personalidade e comportamento." /></Field></div></div><CheckBox label="Marcar como favorito" checked={!!person.favorite} onChange={() => field('favorite', !person.favorite)} /></>}
      </div>}
      {tab === 'ratings' && !quick && <div className="form-section"><div className="rating-summary"><div><h3>Avaliação geral</h3><p>Meias estrelas, do seu jeito.</p></div><strong>{formatNumber(calculateOverallRating(person.rating))}<small>/ 5</small></strong></div><Field label="Como calcular a nota"><select value={person.rating.mode || 'weighted'} onChange={e => setRating('mode', e.target.value)}><option value="weighted">Média ponderada dos atributos</option><option value="manual">Definir minha nota manualmente</option></select></Field>{person.rating.mode === 'manual' && <div className="rating-field"><span>Minha nota geral</span><StarRating label="Nota geral" value={person.rating.overall} onChange={v => setRating('overall', v)} size={27} /></div>}<p className="form-help">Clique na metade esquerda para 0,5 e na direita para uma estrela inteira. Valores não preenchidos não entram na média.</p><div className="rating-fields">{RATING_FIELDS.filter(f => !f.adult || adult).map(f => <div className="rating-field" key={f.key}><span>{f.label}<small>Peso {formatNumber(f.weight)}</small></span><StarRating label={f.label} value={person.rating[f.key]} onChange={v => setRating(f.key, v)} size={25} /></div>)}</div>{!adult && <p className="form-help">Idade não informada ou abaixo de 18 anos. Os campos <strong>peitos</strong>, <strong>bunda</strong> e <strong>quadril</strong> permanecem ocultos por segurança, e todas as outras avaliações continuam disponíveis. Se a pessoa for adulta, basta preencher a idade para liberá-los.</p>}</div>}
      {tab === 'notes' && !quick && <div className="form-section"><div className="section-heading"><h3>Notas soltas</h3><Button onClick={() => field('notas', [...person.notas, { id: generateId(), title: 'Nova nota', content: '', type: 'observacao', date: today() }])}><Plus size={16} />Nova nota</Button></div>{!person.notas.length && <EmptyState title="Um lugar para os detalhes" description="Adicione observações, ideias e lembranças em notas separadas." />}<div className="notes-editor">{person.notas.map(note => <div className="note-editor" key={note.id}><div className="note-edit-head"><input aria-label="Título da nota" value={note.title} onChange={e => field('notas', person.notas.map(n => n.id === note.id ? { ...n, title: e.target.value } : n))} /><select aria-label="Tipo da nota" value={note.type} onChange={e => field('notas', person.notas.map(n => n.id === note.id ? { ...n, type: e.target.value as typeof n.type } : n))}>{['observacao', 'rumor', 'confirmado', 'teoria', 'desejo'].map(t => <option key={t} value={t}>{t === 'observacao' ? 'Observação' : t.charAt(0).toUpperCase() + t.slice(1)}</option>)}</select><IconButton label="Excluir nota do rascunho" onClick={() => field('notas', person.notas.filter(n => n.id !== note.id))}><Trash2 size={16} /></IconButton></div><textarea aria-label="Conteúdo da nota" value={note.content} rows={3} onChange={e => field('notas', person.notas.map(n => n.id === note.id ? { ...n, content: e.target.value } : n))} placeholder="Escreva aqui..." /><input type="date" aria-label="Data da nota" value={note.date.slice(0, 10)} onChange={e => field('notas', person.notas.map(n => n.id === note.id ? { ...n, date: e.target.value } : n))} /></div>)}</div></div>}
      {tab === 'photos' && <div className="form-section"><h3>Fotos da ficha</h3><PhotoUploader onFiles={upload} busy={busy} /><div className="edit-photos">{person.fotos.map(photo => <div key={photo.id} className="edit-photo"><button type="button" className="photo-open" onClick={() => setPhotoPreview(photo.url)}><PhotoView src={photo.url} alt={photo.name} /></button><div className="photo-edit-actions"><button type="button" className={photo.isMain ? 'is-main' : ''} onClick={() => field('fotos', person.fotos.map(f => ({ ...f, isMain: f.id === photo.id })))}><Star size={14} fill={photo.isMain ? 'currentColor' : 'none'} />{photo.isMain ? 'Principal' : 'Definir principal'}</button><IconButton label="Remover foto do rascunho" onClick={() => field('fotos', normalizePhotos(person.fotos.filter(f => f.id !== photo.id), person.id))}><Trash2 size={15} /></IconButton></div><select aria-label="Tipo da foto" value={photo.type} onChange={e => field('fotos', person.fotos.map(f => f.id === photo.id ? { ...f, type: e.target.value as Photo['type'] } : f))}>{Object.entries(PHOTO_LABELS).map(([value, label]) => <option value={value} key={value} disabled={value !== 'normal' && !adult}>{label}</option>)}</select></div>)}</div></div>}
    </>}
    <div className="editor-footer"><p><FileText size={14} />{dirty ? draftLabel : quick ? 'Comece pelo nome. Complete o restante depois.' : 'Somente nome e descrição são obrigatórios'}</p><div><Button onClick={() => setPreview(!preview)}>{preview ? 'Continuar editando' : 'Prévia'}</Button><Button onClick={onCancel}>{dirty ? 'Fechar e guardar' : 'Cancelar'}</Button><Button variant="primary" type="submit" disabled={!valid || busy}><Save size={16} />{submitLabel}</Button></div></div>
    {photoPreview && <Modal title="Visualizar foto" onClose={() => setPhotoPreview(null)} wide><img src={photoPreview} alt="Foto da ficha ampliada" className="full-photo" /></Modal>}
  </form>;
}

export function ReadNotes({ person }: { person: Person }) { return <div className="read-notes">{person.notas.map(note => <article key={note.id}><div><span className="note-type">{note.type === 'observacao' ? 'Observação' : note.type}</span><time>{formatDate(note.date)}</time></div><h3>{note.title}</h3><p>{note.content}</p></article>)}{!person.notas.length && <EmptyState icon={FileText} title="Sem notas por enquanto" description="Edite a ficha para guardar uma nova lembrança." />}</div>; }