import { useRef, useState } from 'react';
import { Camera, Check, FileText, Heart, ImagePlus, Link2, Plus, Save, Sparkles, Star, Trash2, Upload, User, Users } from 'lucide-react';
import type { Person, Photo, Vinculo, VinculoPapel } from '../types';
import { ADULT_APPEARANCE_TAGS, ALTURA_OPTIONS, CABELO_COR_OPTIONS, CABELO_TIPO_OPTIONS, ESTILO_ROUPA_OPTIONS, FRIENDSHIP_LEVELS, PELE_OPTIONS, PRONOME_OPTIONS, QI_OPTIONS, SIGNO_OPTIONS, TIPO_CORPO_OPTIONS, VINCULO_COMIGO_OPTIONS, VINCULO_PAPEIS, vinculoInverso, vinculoLabel } from '../types';
import { useCatalog } from '../context';
import { ageFromBirthday, calculateOverallRating, findDuplicates, formatDate, formatNumber, friendshipLabel, generateId, getAllTagNames, isAdult, normalizePhotos, PHOTO_LABELS, rarityFor, RARITY_LABELS, readImage, RATING_FIELDS, safeLink, today, upcomingBirthday } from '../store';
import { Button, CheckBox, EmptyState, Field, IconButton, Modal, PhotoView } from './ui';
import StarRating from './StarRating';

const OPTION_LABELS: Record<string, string> = { medio: 'Médio', trancado: 'Trançado', indigena: 'Indígena', 'abaixo da media': 'Abaixo da média', 'acima da media': 'Acima da média', genio: 'Gênio' };
function Options({ options, value }: { options: string[]; value: string }) { return <><option value="">Não informado</option>{value && !options.includes(value) && <option value={value}>{value}</option>}{options.map(s => <option key={s} value={s}>{OPTION_LABELS[s] || s.charAt(0).toUpperCase() + s.slice(1)}</option>)}</>; }

export function PhotoUploader({ onFiles, busy, large = false }: { onFiles: (files: File[]) => void; busy?: boolean; large?: boolean }) {
  const input = useRef<HTMLInputElement>(null); const [drag, setDrag] = useState(false);
  return <div className={`upload-zone ${drag ? 'drag-over' : ''} ${large ? 'upload-large' : ''}`} onDragOver={e => { e.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); if (!busy) onFiles(Array.from(e.dataTransfer.files)); }}><input ref={input} type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" className="sr-only" aria-label="Selecionar imagens" onChange={e => { onFiles(Array.from(e.target.files || [])); e.target.value = ''; }} /><Upload size={26} strokeWidth={1.5} /><strong>{busy ? 'Preparando imagens...' : 'Arraste suas fotos até aqui'}</strong><span>JPG, PNG, WebP ou GIF, até 20 MB por imagem.</span><Button onClick={() => input.current?.click()} disabled={busy}><ImagePlus size={17} />{busy ? 'Aguarde' : 'Escolher imagens'}</Button></div>;
}

export default function PersonEditor({ person, update, quick = false, onSave, onSaveAndNew, onCancel, dirty, recovered, onDiscard, submitLabel = 'Salvar ficha' }: {
  person: Person; update: (p: Person | ((p: Person) => Person)) => void; quick?: boolean; onSave: () => void; onSaveAndNew?: () => void; onCancel: () => void; dirty: boolean; recovered: boolean; onDiscard: () => void; submitLabel?: string;
}) {
  const { data, notify, commit, status, demo, sound } = useCatalog();
  const [tab, setTab] = useState('info'); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState(false);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null); const [newTag, setNewTag] = useState('');
  const [vinculoPessoa, setVinculoPessoa] = useState(''); const [vinculoPapel, setVinculoPapel] = useState<VinculoPapel>('mae');
  const category = data.categories.find(c => c.value === person.localizacaoOnde);
  const adult = isAdult(person);
  const selectableTags = getAllTagNames(data).filter(tag => adult || !ADULT_APPEARANCE_TAGS.includes(tag));
  const field = <K extends keyof Person>(key: K, value: Person[K]) => update(p => ({ ...p, [key]: value }));
  const setRating = (key: keyof Person['rating'], value: number | string) => update(p => ({ ...p, rating: { ...p.rating, ...(key === 'mode' && value === 'manual' ? { overall: calculateOverallRating(p.rating) } : {}), [key]: value } }));
  const upload = async (files: File[]) => {
    setBusy(true);
    try {
      const images = await Promise.all(files.map(async file => ({ id: generateId(), url: await readImage(file), name: file.name, personId: person.id, isMain: false, type: 'normal' as const, createdAt: new Date().toISOString() })));
      update(p => ({ ...p, fotos: normalizePhotos([...p.fotos, ...images], p.id) }));
      notify(`${images.length} imagem(ns) preparada(s).`);
      sound('shutter');
    } catch (error) { notify((error as Error).message, true); } finally { setBusy(false); }
  };
  const addTag = () => { const name = newTag.trim().toLocaleLowerCase('pt-BR'); if (!name) return; if (!adult && ADULT_APPEARANCE_TAGS.includes(name)) { notify('Essa tag de aparência só pode ser usada em fichas adultas.', true); return; } if (!getAllTagNames(data).includes(name)) commit(d => ({ ...d, settings: { ...d.settings, customTags: [...d.settings.customTags, { nome: name, cor: '#c786ec' }] } }), 'Tag criada.'); update(p => ({ ...p, tags: [...new Set([...p.tags, name])] })); setNewTag(''); };
  const suggestions = [...new Set(data.people
    .filter(other => other.id !== person.id && !other.deletedAt && (!person.localizacaoOnde || other.localizacaoOnde === person.localizacaoOnde))
    .flatMap(other => other.tags))]
    .filter(tag => selectableTags.includes(tag) && !person.tags.includes(tag))
    .sort((a, b) => data.people.filter(other => other.tags.includes(b)).length - data.people.filter(other => other.tags.includes(a)).length)
    .slice(0, 6);
  const potential = findDuplicates({ ...data, people: [...data.people.filter(p => p.id !== person.id), person] }).filter(pair => pair.a.id === person.id || pair.b.id === person.id);
  const invalidLink = (person.attachments || []).some(item => item.url.trim() && !safeLink(item.url));
  const valid = !!person.nome.trim() && (quick || !!person.descricao.trim()) && !invalidLink && (person.idade === null || Number.isInteger(person.idade) && person.idade >= 0 && person.idade <= 120);
  const draftLabel = demo ? 'Rascunho temporário da demonstração.' : status === 'saved' ? 'Rascunho salvo neste dispositivo.' : status === 'error' ? 'A gravação falhou. Confira o aviso de salvamento.' : 'Salvando seu rascunho...';
  return <form className={`person-editor ${quick ? 'quick-editor' : ''}`} onSubmit={e => { e.preventDefault(); if (valid && !busy) onSave(); }}>
    {(dirty || recovered) && <div className="draft-notice"><FileText size={17} /><span>{recovered ? 'Rascunho recuperado. Continue de onde parou.' : draftLabel}</span><button type="button" className="text-action muted" onClick={onDiscard}>Descartar</button></div>}
    {!quick && <div className="editor-tabs"><button type="button" className={tab === 'info' ? 'active' : ''} onClick={() => setTab('info')}><User size={17} />Informações</button><button type="button" className={tab === 'ratings' ? 'active' : ''} onClick={() => setTab('ratings')}><Star size={17} />Avaliações</button><button type="button" className={tab === 'notes' ? 'active' : ''} onClick={() => setTab('notes')}><FileText size={17} />Notas <small>{person.notas.length}</small></button><button type="button" className={tab === 'photos' ? 'active' : ''} onClick={() => setTab('photos')}><Camera size={17} />Fotos <small>{person.fotos.length}</small></button></div>}
    {preview ? <div className="editor-preview"><PhotoView person={person} /><div><p className="eyebrow">Prévia da ficha</p><h2>{person.nome || 'Nome da pessoa'}</h2><StarRating value={calculateOverallRating(person.rating)} readonly /><p>{person.descricao || 'Você poderá completar a descrição depois.'}</p><span className="muted">{category?.label || 'Sem categoria'}</span></div></div> : <>
      {(tab === 'info' || quick) && <div className="editor-info">
        {quick && <div className="quick-photo"><PhotoView person={person} /><Button onClick={() => setTab(tab === 'photos' ? 'info' : 'photos')}><Camera size={16} />{person.fotos.length ? 'Alterar foto' : 'Adicionar foto'}</Button></div>}
        <div className="form-grid"><Field label="Nome *"><input value={person.nome} onChange={e => field('nome', e.target.value)} placeholder="Como a pessoa se chama?" required maxLength={100} /></Field><Field label="Apelido"><input value={person.apelido || ''} onChange={e => field('apelido', e.target.value)} placeholder="Opcional" maxLength={80} /></Field>
          <Field label="Categoria"><select value={person.localizacaoOnde} onChange={e => update(p => ({ ...p, localizacaoOnde: e.target.value, localizacaoSub: '' }))}><option value="">Escolher categoria</option>{data.categories.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}</select></Field>
          <Field label="Subcategoria"><select value={person.localizacaoSub} disabled={!category?.subs?.length} onChange={e => field('localizacaoSub', e.target.value)}><option value="">{category?.subs?.length ? 'Escolher subcategoria' : 'Sem subcategorias'}</option>{category?.subs?.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}</select></Field>
          <Field label={quick ? 'Descrição (opcional)' : 'Descrição *'} className="span-2"><textarea value={person.descricao} onChange={e => field('descricao', e.target.value)} rows={quick ? 2 : 3} placeholder="O que você gostaria de lembrar sobre essa pessoa?" required={!quick} /></Field>
          {!quick && <><Field label="Idade" hint={person.aniversario && ageFromBirthday(person.aniversario) !== null ? `Calculada do aniversário: ${ageFromBirthday(person.aniversario)} anos` : undefined}><input type="number" min={0} max={120} value={person.idade ?? ageFromBirthday(person.aniversario) ?? ''} onChange={e => field('idade', e.target.value === '' ? null : Number(e.target.value))} placeholder="Não informada" /></Field><Field label="Aniversário" hint={upcomingBirthday(person.aniversario) !== null ? `Faltam ${upcomingBirthday(person.aniversario)} dias` : undefined}><input type="date" value={person.aniversario || ''} onChange={e => { const value = e.target.value || null; update(p => ({ ...p, aniversario: value, idade: value && ageFromBirthday(value) !== null ? ageFromBirthday(value) : p.idade })); }} /></Field><Field label="Altura"><select value={person.altura} onChange={e => field('altura', e.target.value)}><Options options={ALTURA_OPTIONS} value={person.altura} /></select></Field><Field label="Redes sociais / WhatsApp"><input value={person.redesSociais} onChange={e => field('redesSociais', e.target.value)} placeholder="Contato ou @usuário" /></Field><Field label="Onde mora / localização"><input list={`locations-${person.id}`} value={person.localizacaoMora} onChange={e => field('localizacaoMora', e.target.value)} placeholder="Bairro, cidade ou local" /><datalist id={`locations-${person.id}`}>{data.locations.map(s => <option key={s} value={s} />)}</datalist></Field><Field label="Último visto / interação"><input type="date" value={person.ultimoVisto || ''} max={today()} onChange={e => field('ultimoVisto', e.target.value || null)} /></Field><Field label="Q.I. (anotação pessoal)"><select value={person.qi} onChange={e => field('qi', e.target.value)}><Options options={QI_OPTIONS} value={person.qi} /></select></Field>
<Field label="Pronomes"><select value={person.pronome || ''} onChange={e => field('pronome', e.target.value)}><option value="">Não informado</option>{PRONOME_OPTIONS.map(p => <option key={p} value={p}>{p}</option>)}</select></Field>
<Field label="Signo"><select value={person.signo || ''} onChange={e => field('signo', e.target.value)}><option value="">Não informado</option>{SIGNO_OPTIONS.map(p => <option key={p} value={p}>{p}</option>)}</select></Field>
<Field label="Como conheceu"><input value={person.comoConheceu || ''} onChange={e => field('comoConheceu', e.target.value)} placeholder="Ex.: Na festa da Ana, trabalho..." /></Field>
<Field label="Música favorita"><input value={person.musicaFavorita || ''} onChange={e => field('musicaFavorita', e.target.value)} placeholder="Artista, banda ou música" /></Field>
</>}
        </div>
        <div className="friendship-level">
          <div><h3>Nível de amizade</h3><p>Este dado é independente da avaliação e nunca altera a nota geral.</p></div>
          <div className="friendship-control"><input type="range" min="0" max="5" step="1" value={person.friendshipLevel || 0} aria-label="Nível de amizade" onChange={e => field('friendshipLevel', Number(e.target.value))} /><div>{FRIENDSHIP_LEVELS.map(level => <button type="button" key={level.value} className={(person.friendshipLevel || 0) === level.value ? 'active' : ''} onClick={() => field('friendshipLevel', level.value)} aria-label={level.label}>{level.value}</button>)}</div><strong>{friendshipLabel(person.friendshipLevel)}</strong></div>
        </div>
        {potential.length > 0 && <div className="inline-notice warning"><FileText size={17} />{potential.length} possível(is) duplicata(s) por nome ou contato. Confira em Organizar antes de salvar.</div>}
        <div className="form-section"><h3>Tags</h3><div className="tag-picker">{selectableTags.map(tag => <button type="button" key={tag} aria-pressed={person.tags.includes(tag)} className={person.tags.includes(tag) ? 'selected' : ''} onClick={() => field('tags', person.tags.includes(tag) ? person.tags.filter(t => t !== tag) : [...person.tags, tag])}>{person.tags.includes(tag) && <Check size={12} />}{tag}</button>)}</div>{!adult && <p className="form-help">As etiquetas de aparência (gostosa, bonita, bonitinha, cavala, gata, gatinha, dá pra ir) continuam salvas, mas só aparecem na paleta quando a ficha informa 18 anos ou mais. Todas as outras etiquetas ficam sempre disponíveis.</p>}{suggestions.length > 0 && <div className="tag-suggestions"><span>Sugestões desta categoria:</span>{suggestions.map(tag => <button type="button" key={tag} disabled={person.tags.includes(tag)} onClick={() => field('tags', [...person.tags, tag])}><Plus size={11} />{tag}</button>)}</div>}
        <div className="form-section family-section"><h3><Users size={16} />Família e vínculos</h3>
          <div className="form-grid">
            <Field label="O que ela é sua" hint="Muda a dinâmica da conversa: tia, prima, líder, colega..."><select value={person.vinculoComigo || ''} onChange={e => field('vinculoComigo', e.target.value)}>{VINCULO_COMIGO_OPTIONS.map(opcao => <option key={opcao.value} value={opcao.value}>{opcao.label}</option>)}</select></Field>
            <Field label="Idade dela" hint={person.idade ? `${person.idade} anos — a conversa compara com a sua idade.` : 'Sem idade, a conversa não sabe se você é mais novo.'}><span className="family-age">{person.idade ? `${person.idade} anos` : 'Não informada'}</span></Field>
            <Field label="Jeito de falar" hint="A idade já sugere a maturidade. Aqui você ajusta o vocabulário da conversa sem mexer na idade."><select aria-label="Jeito de falar" value={person.maturidadeAjuste || 'auto'} onChange={e => field('maturidadeAjuste', e.target.value as 'auto' | 'seria' | 'solta')}><option value="auto">Como a idade sugere</option><option value="seria">Mais séria e contida</option><option value="solta">Mais solta e brincalhona</option></select></Field>
          </div>
          <div className="family-add">
            <select aria-label="Familiar no catálogo" value={vinculoPessoa} onChange={e => setVinculoPessoa(e.target.value)}><option value="">Quem é da família dela?</option>{data.people.filter(outra => outra.id !== person.id && !outra.deletedAt).map(outra => <option key={outra.id} value={outra.id}>{outra.nome}</option>)}</select>
            <select aria-label="Papel do familiar" value={vinculoPapel} onChange={e => setVinculoPapel(e.target.value as VinculoPapel)}>{VINCULO_PAPEIS.map(opcao => <option key={opcao.value} value={opcao.value}>{opcao.label}</option>)}</select>
            <Button onClick={() => { if (!vinculoPessoa) { notify('Escolha quem é da família dela.', true); return; } const novo: Vinculo = { id: generateId(), personId: vinculoPessoa, papel: vinculoPapel }; field('vinculos', [...(person.vinculos || []), novo]); setVinculoPessoa(''); notify(`${VINCULO_PAPEIS.find(p => p.value === vinculoPapel)?.label || 'Vínculo'} adicionado.`); }}><Plus size={15} />Vincular</Button>
          </div>
          <ul className="family-list">{(person.vinculos || []).map(vinculo => { const outra = data.people.find(p => p.id === vinculo.personId); return <li key={vinculo.id}><Heart size={13} /><span>{vinculoLabel(vinculo.papel)} de {outra?.nome || 'ficha removida'}{outra && <small>E o vínculo de volta entra sozinho: {outra.nome.split(' ')[0]} fica como {vinculoInverso(vinculo.papel)} na ficha dela</small>}</span><IconButton label={`Remover vínculo com ${outra?.nome || 'ficha'}`} onClick={() => field('vinculos', (person.vinculos || []).filter(item => item.id !== vinculo.id))}><Trash2 size={15} /></IconButton></li>; })}{!(person.vinculos || []).length && <li className="muted">Nenhum familiar vinculado. Ligue a mãe, a filha, a irmã — a conversa passa a falar delas pelo nome.</li>}</ul>
          <p className="form-help">Os vínculos valem nos dois sentidos: ao ligar alguém aqui, o papel inverso também aparece na outra ficha, e o simulador de conversa usa esses nomes.</p>
        </div>
        <div className="inline-create"><input value={newTag} onChange={e => setNewTag(e.target.value)} placeholder="Nova tag" aria-label="Nome da nova tag" onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addTag(); } }} /><Button onClick={addTag} disabled={!newTag.trim()}><Plus size={15} />Criar tag</Button></div></div>
        {!quick && <><div className="form-section"><h3>Aparência e características</h3><div className="form-grid"><Field label="Tipo de cabelo"><select value={person.cabeloTipo} onChange={e => field('cabeloTipo', e.target.value)}><Options options={CABELO_TIPO_OPTIONS} value={person.cabeloTipo} /></select></Field><Field label="Cor do cabelo"><select value={person.cabeloCor} onChange={e => field('cabeloCor', e.target.value)}><Options options={CABELO_COR_OPTIONS} value={person.cabeloCor} /></select></Field>{person.cabeloCor === 'colorido' && <Field label="Qual cor?"><input value={person.cabeloCorCustom} onChange={e => field('cabeloCorCustom', e.target.value)} /></Field>}<Field label="Tom de pele"><select value={person.pele} onChange={e => field('pele', e.target.value)}><Options options={PELE_OPTIONS} value={person.pele} /></select></Field>{person.pele === 'personalizado' && <Field label="Tom personalizado"><input value={person.peleCustom} onChange={e => field('peleCustom', e.target.value)} /></Field>}<Field label="Tipo de corpo"><select value={person.tipoCorpo || ''} onChange={e => field('tipoCorpo', e.target.value)}><Options options={TIPO_CORPO_OPTIONS} value={person.tipoCorpo || ''} /></select></Field><Field label="Estilo de roupa"><select value={person.estiloRoupa || ''} onChange={e => field('estiloRoupa', e.target.value)}><Options options={ESTILO_ROUPA_OPTIONS} value={person.estiloRoupa || ''} /></select></Field><Field label="Descrição corporal" className="span-2"><textarea rows={3} value={person.descricaoCorporal} onChange={e => field('descricaoCorporal', e.target.value)} placeholder="Características, tatuagens, piercings ou outros detalhes." /></Field><Field label="Observações gerais" className="span-2"><textarea rows={3} value={person.observacoesGerais || ''} onChange={e => field('observacoesGerais', e.target.value)} placeholder="Anotações gerais que não entram em nenhuma seção específica." /></Field><Field label="Comportamento" className="span-2"><textarea rows={3} value={person.comportamento} onChange={e => field('comportamento', e.target.value)} placeholder="Anotações sobre personalidade e comportamento." /></Field></div></div><div className="form-section"><h3><Sparkles size={16} />Raridade automática</h3><div className="rarity-picker">{['comum', 'raro', 'epico', 'lendario'].map(value => <button type="button" key={value} className={`rarity-chip rarity-${value} ${person.rarity === value ? 'selected' : ''}`} onClick={() => field('rarity', value as Person['rarity'])}>{RARITY_LABELS[value]}{rarityFor(calculateOverallRating(person.rating)) === value && <small>sugerida</small>}</button>)}</div><p className="form-help">A sugestão vem da nota atual ({formatNumber(calculateOverallRating(person.rating))}). Você pode escolher outra manualmente.</p></div>
          <div className="form-section"><h3><FileText size={16} />Campos personalizados</h3><div className="custom-fields">{(person.customFields || []).map(custom => <div className="custom-field" key={custom.id}><input aria-label="Nome do campo" value={custom.label} placeholder="Ex.: Signo" onChange={e => field('customFields', (person.customFields || []).map(item => item.id === custom.id ? { ...item, label: e.target.value } : item))} /><input aria-label="Valor do campo" value={custom.value} placeholder="Ex.: Leão" onChange={e => field('customFields', (person.customFields || []).map(item => item.id === custom.id ? { ...item, value: e.target.value } : item))} /><IconButton label="Remover campo" onClick={() => field('customFields', (person.customFields || []).filter(item => item.id !== custom.id))}><Trash2 size={15} /></IconButton></div>)}<Button onClick={() => field('customFields', [...(person.customFields || []), { id: generateId(), label: '', value: '' }])}><Plus size={15} />Novo campo</Button></div><p className="form-help">Crie campos do seu jeito: signo, profissão, time, qualquer coisa. Eles entram na busca do catálogo.</p></div>
          <div className="form-section"><h3><Link2 size={16} />Anexos e links</h3><div className="attachment-list">{(person.attachments || []).map(item => <div className="attachment-row" key={item.id}><input aria-label="Nome do anexo" value={item.label} placeholder="Ex.: Vídeo do aniversário" onChange={e => field('attachments', (person.attachments || []).map(x => x.id === item.id ? { ...x, label: e.target.value } : x))} /><select aria-label="Tipo do anexo" value={item.kind} onChange={e => field('attachments', (person.attachments || []).map(x => x.id === item.id ? { ...x, kind: e.target.value as typeof x.kind } : x))}>{['link', 'video', 'pdf', 'audio', 'outro'].map(kind => <option key={kind} value={kind}>{kind === 'outro' ? 'Outro' : kind.toUpperCase()}</option>)}</select><input aria-label="Endereço do anexo" value={item.url} placeholder="https://..." onChange={e => field('attachments', (person.attachments || []).map(x => x.id === item.id ? { ...x, url: e.target.value } : x))} /><IconButton label="Remover anexo" onClick={() => field('attachments', (person.attachments || []).filter(x => x.id !== item.id))}><Trash2 size={15} /></IconButton></div>)}<Button onClick={() => field('attachments', [...(person.attachments || []), { id: generateId(), label: '', url: '', kind: 'link', createdAt: new Date().toISOString() }])}><Plus size={15} />Novo anexo</Button></div><p className="form-help">Só endereços http(s), mailto: ou tel: são aceitos, por segurança.</p></div>
          {(person.ratingHistory || []).length > 1 && <div className="form-section"><h3><Star size={16} />Histórico da nota</h3><ul className="rating-history">{(person.ratingHistory || []).slice(-6).map((entry, index) => <li key={`${entry.date}-${index}`}><time>{formatDate(entry.date)}</time><strong>{formatNumber(entry.overall)}</strong></li>)}</ul></div>}
          <CheckBox label="Marcar como favorito" checked={!!person.favorite} onChange={() => field('favorite', !person.favorite)} /></>}
      </div>}
      {tab === 'ratings' && !quick && <div className="form-section"><div className="rating-summary"><div><h3>Avaliação geral</h3><p>Meias estrelas, do seu jeito.</p></div><strong>{formatNumber(calculateOverallRating(person.rating))}<small>/ 5</small></strong></div><Field label="Como calcular a nota"><select value={person.rating.mode || 'weighted'} onChange={e => setRating('mode', e.target.value)}><option value="weighted">Média ponderada dos atributos</option><option value="manual">Definir minha nota manualmente</option></select></Field>{person.rating.mode === 'manual' && <div className="rating-field"><span>Minha nota geral</span><StarRating label="Nota geral" value={person.rating.overall} onChange={v => setRating('overall', v)} size={27} /></div>}<p className="form-help">Clique na metade esquerda para 0,5 e na direita para uma estrela inteira. Valores não preenchidos não entram na média.</p><div className="rating-fields">{RATING_FIELDS.filter(f => !f.adult || adult).map(f => <div className="rating-field" key={f.key}><span>{f.label}<small>Peso {formatNumber(f.weight)}</small></span><StarRating label={f.label} value={person.rating[f.key]} onChange={v => setRating(f.key, v)} size={25} /></div>)}</div>{!adult && <p className="form-help">Idade não informada ou abaixo de 18 anos. Os campos <strong>peitos</strong>, <strong>bunda</strong> e <strong>quadril</strong> permanecem ocultos por segurança, e todas as outras avaliações continuam disponíveis. Se a pessoa for adulta, basta preencher a idade para liberá-los.</p>}</div>}
      {tab === 'notes' && !quick && <div className="form-section"><div className="section-heading"><h3>Notas soltas</h3><Button onClick={() => field('notas', [...person.notas, { id: generateId(), title: 'Nova nota', content: '', type: 'observacao', date: today() }])}><Plus size={16} />Nova nota</Button></div>{!person.notas.length && <EmptyState title="Um lugar para os detalhes" description="Adicione observações, ideias e lembranças em notas separadas." />}<div className="notes-editor">{person.notas.map(note => <div className="note-editor" key={note.id}><div className="note-edit-head"><input aria-label="Título da nota" value={note.title} onChange={e => field('notas', person.notas.map(n => n.id === note.id ? { ...n, title: e.target.value } : n))} /><select aria-label="Tipo da nota" value={note.type} onChange={e => field('notas', person.notas.map(n => n.id === note.id ? { ...n, type: e.target.value as typeof n.type } : n))}>{['observacao', 'rumor', 'confirmado', 'teoria', 'desejo'].map(t => <option key={t} value={t}>{t === 'observacao' ? 'Observação' : t.charAt(0).toUpperCase() + t.slice(1)}</option>)}</select><IconButton label="Excluir nota do rascunho" onClick={() => field('notas', person.notas.filter(n => n.id !== note.id))}><Trash2 size={16} /></IconButton></div><textarea aria-label="Conteúdo da nota" value={note.content} rows={3} onChange={e => field('notas', person.notas.map(n => n.id === note.id ? { ...n, content: e.target.value } : n))} placeholder="Escreva aqui..." /><input type="date" aria-label="Data da nota" value={note.date.slice(0, 10)} onChange={e => field('notas', person.notas.map(n => n.id === note.id ? { ...n, date: e.target.value } : n))} /></div>)}</div></div>}
      {tab === 'photos' && <div className="form-section"><h3>Fotos da ficha</h3><PhotoUploader onFiles={upload} busy={busy} /><div className="edit-photos">{person.fotos.map(photo => <div key={photo.id} className="edit-photo"><button type="button" className="photo-open" onClick={() => setPhotoPreview(photo.url)}><PhotoView src={photo.url} alt={photo.name} /></button><div className="photo-edit-actions"><button type="button" className={photo.isMain ? 'is-main' : ''} onClick={() => field('fotos', person.fotos.map(f => ({ ...f, isMain: f.id === photo.id })))}><Star size={14} fill={photo.isMain ? 'currentColor' : 'none'} />{photo.isMain ? 'Principal' : 'Definir principal'}</button><IconButton label="Remover foto do rascunho" onClick={() => field('fotos', normalizePhotos(person.fotos.filter(f => f.id !== photo.id), person.id))}><Trash2 size={15} /></IconButton></div><select aria-label="Tipo da foto" value={photo.type} onChange={e => field('fotos', person.fotos.map(f => f.id === photo.id ? { ...f, type: e.target.value as Photo['type'] } : f))}>{Object.entries(PHOTO_LABELS).map(([value, label]) => <option value={value} key={value} disabled={value !== 'normal' && !adult}>{label}</option>)}</select></div>)}</div></div>}
    </>}
    <div className="editor-footer"><p><FileText size={14} />{invalidLink ? 'Um anexo tem endereço inválido. Use http(s), mailto: ou tel:.' : dirty ? draftLabel : quick ? 'Comece pelo nome. Complete o restante depois.' : 'Somente nome e descrição são obrigatórios'}</p><div><Button onClick={() => setPreview(!preview)}>{preview ? 'Continuar editando' : 'Prévia'}</Button><Button onClick={onCancel}>{dirty ? 'Fechar e guardar' : 'Cancelar'}</Button>{onSaveAndNew && <Button type="button" disabled={!valid || busy} onClick={() => { if (valid && !busy) onSaveAndNew(); }}><Plus size={16} />Salvar e adicionar outra</Button>}<Button variant="primary" type="submit" disabled={!valid || busy}><Save size={16} />{submitLabel}</Button></div></div>
    {photoPreview && <Modal title="Visualizar foto" onClose={() => setPhotoPreview(null)} wide><img src={photoPreview} alt="Foto da ficha ampliada" className="full-photo" /></Modal>}
  </form>;
}

export function ReadNotes({ person }: { person: Person }) { return <div className="read-notes">{person.notas.map(note => <article key={note.id}><div><span className="note-type">{note.type === 'observacao' ? 'Observação' : note.type}</span><time>{formatDate(note.date)}</time></div><h3>{note.title}</h3><p>{note.content}</p></article>)}{!person.notas.length && <EmptyState icon={FileText} title="Sem notas por enquanto" description="Edite a ficha para guardar uma nova lembrança." />}</div>; }