import { useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowRight, ChevronDown, Crown, Download, Eye, FileJson, Flame as FlameIcon, Info, Layers, ListOrdered, Printer, Trophy } from 'lucide-react';
import { motion } from 'framer-motion';
import { useCatalog } from '../context';
import { calculateOverallRating, downloadJson, exportCsv, formatNumber, getFinalScore, locationLabel, rankedPeople, today } from '../store';
import { exportRankingPng } from '../lib/export';
import { Avatar, Button, EmptyState, IconButton, PageTitle } from './ui';
import StarRating from './StarRating';

function Flame({ size, title }: { size: number; title: string }) { return <span title={title}><FlameIcon size={size} aria-label={title} /></span>; }

export default function Ranking() {
  const ctx = useCatalog(), { data } = ctx;
  const [category, setCategory] = useState(''); const [subcategory, setSubcategory] = useState('');
  const [mode, setMode] = useState<'points' | 'tier'>('points'); const [exportMenu, setExportMenu] = useState(false); const [busy, setBusy] = useState(false); const [rules, setRules] = useState(false);
  const results = useMemo(() => rankedPeople(data.people).filter(p => (!category || p.localizacaoOnde === category) && (!subcategory || p.localizacaoSub === subcategory)), [data.people, category, subcategory]);
  const cat = data.categories.find(c => c.value === category);
  const label = [cat?.label || 'Todas as categorias', cat?.subs?.find(s => s.value === subcategory)?.label].filter(Boolean).join(' / ');
  const exportImage = async (full: boolean) => {
    if (ctx.privacy) return; setBusy(true); setExportMenu(false);
    try { await exportRankingPng(results, data, full, label); ctx.notify(`${full ? 'Ranking' : 'Pódio'} exportado em PNG.`); } catch (error) { ctx.notify((error as Error).message, true); } finally { setBusy(false); }
  };
  const exportJson = () => { downloadJson({ categoria: category || 'todas', subcategoria: subcategory || 'todas', dataExportacao: new Date().toISOString(), total: results.length, ranking: results.map((p, i) => ({ posicao: i + 1, nome: p.nome, notaBase: calculateOverallRating(p.rating), pontos: getFinalScore(p), localizacao: locationLabel(p, data), tags: p.tags })) }, `catalog-ranking-${today()}.json`); setExportMenu(false); };
  return <div className="ranking-page"><PageTitle eyebrow="As conexões em destaque" title="Seu ranking" description="Suas avaliações, em uma perspectiva especial."><div className="menu-anchor"><Button variant="primary" disabled={busy || !results.length} onClick={() => setExportMenu(!exportMenu)}><ArrowDownToLine size={17} />{busy ? 'Preparando imagem...' : 'Exportar ranking'}<ChevronDown size={14} /></Button>{exportMenu && <div className="dropdown-menu"><button onClick={() => exportImage(false)}><Trophy size={16} />Pódio em PNG</button><button onClick={() => exportImage(true)}><Download size={16} />Ranking completo em PNG</button><button onClick={exportJson}><FileJson size={16} />Dados em JSON</button><button onClick={() => { exportCsv(results, data); setExportMenu(false); }}><ListOrdered size={16} />Planilha CSV</button><button onClick={() => { setExportMenu(false); window.print(); }}><Printer size={16} />Imprimir / salvar PDF</button></div>}</div></PageTitle>
    <div className="ranking-toolbar no-print"><div className="segmented"><button className={mode === 'points' ? 'active' : ''} onClick={() => setMode('points')}><ListOrdered size={16} />Por pontos</button><button className={mode === 'tier' ? 'active' : ''} onClick={() => setMode('tier')}><Layers size={16} />Por faixas</button></div><div className="ranking-filter-group"><select value={category} aria-label="Categoria do ranking" onChange={e => { setCategory(e.target.value); setSubcategory(''); }}><option value="">Todas as categorias</option>{data.categories.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}</select>{cat?.subs?.length ? <select value={subcategory} onChange={e => setSubcategory(e.target.value)} aria-label="Subcategoria do ranking"><option value="">Todas as subcategorias</option>{cat.subs.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}</select> : null}<button className="text-action muted" onClick={() => setRules(!rules)}><Info size={16} />Como calculamos</button></div></div>
    {rules && <div className="ranking-rules no-print"><Info size={18} /><div><strong>Uma nota consistente em todo o app.</strong><p>A nota geral usa os pesos indicados na ficha ou sua nota manual. A tag crush acrescenta 0,5 ponto a fichas avaliadas, respeitando o limite de 5. Empates são ordenados pela nota base e, depois, pelo nome. Fichas arquivadas ou na lixeira não participam.</p></div></div>}
    {!results.length ? <EmptyState icon={Trophy} title="Seu próximo destaque começa aqui" description="Adicione pessoas ou escolha outra categoria para montar seu pódio." action="Adicionar pessoa" onAction={() => ctx.navigate('add')} /> : <div className="print-region ranking-print">
      <div className="print-only"><h1>Ranking do Catalog</h1><p>{label}</p></div>
      {mode === 'points' ? <><div className="podium-stage"><div className="podium-aura" /><div className="podium-caption"><span className="eyebrow">O melhor do seu catálogo</span><h2>Encontros que se destacam.</h2></div><div className="podium-people">{[{ i: 1, metal: 'silver' }, { i: 0, metal: 'gold' }, { i: 2, metal: 'bronze' }].map(({ i, metal }) => {
        const p = results[i];
        return <motion.div className={`podium-place ${metal} ${p ? '' : 'empty-place'}`} key={metal} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1, duration: 0.55 }}><div className="podium-person">{p ? <>{i === 0 && <Crown className="podium-crown" size={31} fill="currentColor" strokeWidth={1.3} />}<button className="podium-avatar" onClick={() => ctx.openPerson(p)} aria-label={`Abrir ficha de ${p.nome}`}><Avatar person={p} size={i === 0 ? 146 : 128} /></button><button className="podium-name" onClick={() => ctx.openPerson(p)}>{p.nome}</button><p className="podium-location">{locationLabel(p, data, false)}</p><div className="podium-score"><strong>{formatNumber(getFinalScore(p))}</strong><small>pontos</small>{p.tags.includes('crush') && <Flame size={15} title="Bônus crush: +0,5" />}</div><StarRating value={calculateOverallRating(p.rating)} readonly size={13} showValue={false} /></> : <><span className="podium-empty-avatar"><Trophy size={30} /></span><p>Seu próximo destaque</p></>}</div><div className="pedestal"><span className="pedestal-top" /><span className="pedestal-number">{i + 1}<small>º</small></span><span className="pedestal-label">{i === 0 ? 'PRIMEIRO LUGAR' : i === 1 ? 'SEGUNDO LUGAR' : 'TERCEIRO LUGAR'}</span></div></motion.div>;
      })}</div><div className="podium-floor" /></div>
      {results.length > 3 && <section className="ranking-list"><div className="section-heading"><h2>Todos os destaques</h2><span className="muted small">{results.length} pessoas no ranking</span></div><table><thead><tr><th>Posição</th><th>Pessoa</th><th>Avaliação</th><th>Categoria</th><th className="no-print">Ações</th></tr></thead><tbody>{results.slice(3).map((p, i) => <tr key={p.id}><td className="rank-number">{String(i + 4).padStart(2, '0')}</td><td><button className="table-person" onClick={() => ctx.openPerson(p)}><Avatar person={p} size={48} /><span>{p.nome}<small>{p.apelido || 'Ver ficha'}</small></span>{p.favorite && <span className="favorite-dot" />}</button></td><td><div className="table-score"><strong>{formatNumber(getFinalScore(p))}</strong><StarRating value={calculateOverallRating(p.rating)} size={12} readonly showValue={false} /></div></td><td className="muted">{locationLabel(p, data)}</td><td className="no-print"><div className="table-actions"><IconButton label="Registrar interação hoje" onClick={() => ctx.seenToday([p.id])}><Eye size={17} /></IconButton><IconButton label="Abrir ficha" onClick={() => ctx.openPerson(p)}><ArrowRight size={17} /></IconButton></div></td></tr>)}</tbody></table></section>}</> : <div className="automatic-tiers"><div className="section-heading"><h2>Classificação automática</h2><button className="text-action no-print" onClick={() => ctx.navigate('tierlists')}>Organizar minha tierlist<ArrowRight size={15} /></button></div>{[{ tier: 'S', min: 4.5, max: 5.01, color: '#df9ea8' }, { tier: 'A', min: 3.5, max: 4.5, color: '#dab68f' }, { tier: 'B', min: 2.5, max: 3.5, color: '#d6c381' }, { tier: 'C', min: 1.5, max: 2.5, color: '#8eb7a0' }, { tier: 'D', min: 0, max: 1.5, color: '#8ba9c5' }].map(t => <div key={t.tier} className="tier-row"><div className="tier-label" style={{ backgroundColor: `${t.color}20`, color: t.color }}><strong>{t.tier}</strong><small>{t.min.toLocaleString('pt-BR')} a {Math.min(5, t.max).toLocaleString('pt-BR')}</small></div><div className="tier-dropzone">{results.filter(p => getFinalScore(p) >= t.min && getFinalScore(p) < t.max).map(p => <button className="tier-person" key={p.id} onClick={() => ctx.openPerson(p)}><Avatar person={p} size={40} /><span>{p.nome}<small>{formatNumber(getFinalScore(p))} pontos</small></span></button>)}</div></div>)}</div>}
      <p className="ranking-footnote"><Info size={13} />Notas pessoais e subjetivas. O ranking não representa o valor de uma pessoa.</p>
    </div>}
  </div>;
}