import { useState } from 'react';
import { Bell, CalendarClock, Check, Clock3, Edit3, Plus, Trash2 } from 'lucide-react';
import type { Reminder } from '../types';
import { useCatalog } from '../context';
import { addDays, DEADLINE_LABELS, deadlineState, daysUntil, formatDate, generateId, today } from '../store';
import { notificationPermission, requestNotificationPermission } from '../lib/notifications';
import { AlarmClock, BellRing } from 'lucide-react';
import { Avatar, Button, Confirm, EmptyState, Field, IconButton, Modal, PageTitle, SectionHeading } from './ui';

export default function Reminders({ compact = false }: { compact?: boolean }) {
  const ctx = useCatalog(), { data } = ctx;
  const [permission, setPermission] = useState<string>(() => notificationPermission());
  const [scope, setScope] = useState('pending'); const [editing, setEditing] = useState<Reminder | null>(null); const [deleting, setDeleting] = useState<string | null>(null);
  const filtered = [...data.reminders].filter(r => scope === 'all' || scope === 'done' ? scope === 'all' || r.concluido : scope === 'overdue' ? !r.concluido && r.data < today() : !r.concluido).sort((a, b) => Number(a.concluido) - Number(b.concluido) || a.data.localeCompare(b.data));
  const shown = compact ? filtered.slice(0, 4) : filtered;
  const create = () => setEditing({ id: generateId(), titulo: '', personId: null, data: today(), concluido: false, createdAt: new Date().toISOString(), priority: 'normal', descricao: '' });
  const save = () => { if (!editing?.titulo.trim() || !editing.data) return; const reminder = { ...editing, titulo: editing.titulo.trim() }; ctx.commit(d => ({ ...d, reminders: d.reminders.some(r => r.id === reminder.id) ? d.reminders.map(r => r.id === reminder.id ? reminder : r) : [...d.reminders, reminder] }), 'Lembrete salvo.'); setEditing(null); };
  const repeatOffset: Record<string, number> = { daily: 1, weekly: 7, monthly: 30, yearly: 365 };
  const toggle = (r: Reminder) => {
    const offset = repeatOffset[r.repeat || 'none'];
    if (!r.concluido && offset) { ctx.commit(d => ({ ...d, reminders: d.reminders.map(x => x.id === r.id ? { ...x, data: addDays(x.data < today() ? today() : x.data, offset), concluido: false, notifiedAt: null } : x) }), `Lembrete concluído e reagendado (repetição ${r.repeat}).`); return; }
    ctx.commit(d => ({ ...d, reminders: d.reminders.map(x => x.id === r.id ? { ...x, concluido: !x.concluido } : x) }), r.concluido ? 'Lembrete reaberto.' : 'Lembrete concluído.');
  };
  const snooze = (r: Reminder, days: number) => ctx.commit(d => ({ ...d, reminders: d.reminders.map(x => x.id === r.id ? { ...x, data: addDays(x.data < today() ? today() : x.data, days), concluido: false } : x) }), `Lembrete adiado por ${days} dia(s).`);
  // Radar de prazos: quanto de cada lembrete pendente está a ponto de vencer.
  const lead = data.settings.notificationLeadDays ?? 3;
  const open = data.reminders.filter(r => !r.concluido);
  const buckets = ['atrasado', 'hoje', 'amanha', 'perto'] as const;
  const urgent = buckets.map(state => ({ state, label: DEADLINE_LABELS[state], items: open.filter(r => deadlineState(r.data, lead).state === state) }));
  const upcoming = [...open].filter(r => { const { state } = deadlineState(r.data, lead); return state === 'atrasado' || state === 'hoje' || state === 'amanha' || state === 'perto'; }).sort((a, b) => (deadlineState(a.data, lead).days ?? 999) - (deadlineState(b.data, lead).days ?? 999));
  const askPermission = async () => { setPermission(await requestNotificationPermission()); ctx.notify(permission === 'granted' ? 'As notificações já estão liberadas.' : permission === 'denied' ? 'O navegador bloqueou notificações para este site. Libere no endereço (ícone de cadeado) e recarregue.' : 'Notificações liberadas. Você será avisada antes dos prazos.'); };
  return <section className={compact ? 'reminders-preview' : 'reminders-page'}>{compact ? <SectionHeading icon={Bell} title="Para não esquecer" action="Ver lembretes" onAction={() => ctx.navigate('reminders')} /> : <><PageTitle eyebrow="Um cuidado com as suas conexões" title="Lembretes" description="Pequenos lembretes para não deixar os bons momentos passarem."><Button variant="primary" onClick={create}><Plus size={18} />Novo lembrete</Button></PageTitle><div className="scope-tabs">{[['pending', 'Pendentes'], ['overdue', 'Atrasados'], ['done', 'Concluídos'], ['all', 'Todos']].map(([value, label]) => <button key={value} className={scope === value ? 'active' : ''} onClick={() => setScope(value)}>{label}</button>)}</div><p className="form-help"><Bell size={14} />Os lembretes viram avisos na central e, se você permitir, notificações do navegador quando o prazo estiver chegando. <button className="text-action" onClick={() => ctx.navigate('settings')}>Configurar avisos</button></p>
      {permission !== 'granted' && <div className="permission-line"><BellRing size={15} /><span>Ative as notificações do navegador para ser avisada {lead} dia(s) antes dos prazos.</span><Button onClick={askPermission}>Permitir notificações</Button></div>}
      <div className="deadline-board">
        {urgent.map(({ state, label, items }) => <button key={state} className={`deadline-card deadline-${state}`} onClick={() => setScope(state === 'atrasado' ? 'overdue' : 'pending')}><strong>{items.length}</strong><span><AlarmClock size={13} />{label}</span>{items.length === 1 && <small>{items[0].titulo}</small>}{items.length > 1 && <small>{items.slice(0, 2).map(item => item.titulo).join(' · ')}…</small>}</button>)}
      </div>
      {upcoming.length > 0 && <div className="deadline-list"><h3><AlarmClock size={15} />O que está perto do prazo</h3><ul>{upcoming.slice(0, 6).map(r => { const { state, days } = deadlineState(r.data, lead); return <li key={r.id} className={`deadline-${state}`}><button onClick={() => setEditing(r)}>{r.titulo}</button><span>{DEADLINE_LABELS[state]}{days !== null && days > 0 && ` · ${days === 1 ? '1 dia' : `${days} dias`}`}</span></li>; })}</ul></div>}</>}
    <div className="reminder-list">{shown.map(r => { const person = data.people.find(p => p.id === r.personId); const overdue = !r.concluido && r.data < today(); return <div key={r.id} className={`reminder-row ${r.concluido ? 'completed' : ''}`}><button className={`complete-reminder ${r.concluido ? 'checked' : ''}`} onClick={() => toggle(r)} aria-label={r.concluido ? `Reabrir ${r.titulo}` : `Concluir ${r.titulo}`}>{r.concluido && <Check size={15} />}</button><div className="reminder-content"><button onClick={() => setEditing(r)}><strong>{r.titulo}</strong></button><span className={overdue ? 'overdue' : ''}><CalendarClock size={13} />{overdue ? 'Atrasado · ' : r.data === today() ? 'Hoje · ' : ''}{formatDate(r.data)}{r.priority === 'alta' && <small>Prioridade alta</small>}{!r.concluido && daysUntil(r.data) !== null && daysUntil(r.data)! > 0 && <small> · {daysUntil(r.data) === 1 ? 'falta 1 dia' : `faltam ${daysUntil(r.data)} dias`}</small>}{(r.repeat || 'none') !== 'none' && <small> · repete</small>}</span>{!compact && r.descricao && <p>{r.descricao}</p>}</div>{person && <button className="reminder-person" onClick={() => ctx.openPerson(person)}><Avatar person={person} size={31} /><span>{person.nome}{person.deletedAt && <small>Na lixeira</small>}</span></button>}<div className="reminder-actions">{!r.concluido && <details className="details-menu"><summary className="icon-btn" title="Adiar lembrete" aria-label="Adiar lembrete"><Clock3 size={16} /></summary><div className="dropdown-menu"><button onClick={() => snooze(r, 1)}>Adiar por 1 dia</button><button onClick={() => snooze(r, 7)}>Adiar por 7 dias</button><button onClick={() => snooze(r, 30)}>Adiar por 30 dias</button></div></details>}<IconButton label="Editar lembrete" onClick={() => setEditing(r)}><Edit3 size={16} /></IconButton>{!compact && <IconButton label="Excluir lembrete" onClick={() => setDeleting(r.id)}><Trash2 size={16} /></IconButton>}</div></div>; })}</div>
    {!shown.length && (compact ? <div className="reminders-empty"><span><Bell size={17} />Tudo em dia. Crie um lembrete para um próximo encontro.</span><button className="text-action" onClick={create}><Plus size={14} />Adicionar lembrete</button></div> : <EmptyState icon={Bell} title={scope === 'done' ? 'Os concluídos aparecerão aqui' : 'Tudo em dia por aqui'} description="Crie lembretes com datas e pessoas vinculadas, e conclua quando terminar." action="Criar lembrete" onAction={create} />)}
    {editing && <Modal title={data.reminders.some(r => r.id === editing.id) ? 'Editar lembrete' : 'Novo lembrete'} onClose={() => setEditing(null)} footer={<><Button onClick={() => setEditing(null)}>Cancelar</Button><Button variant="primary" disabled={!editing.titulo.trim() || !editing.data} onClick={save}><Check size={16} />Salvar lembrete</Button></>}><Field label="O que você quer lembrar?"><input value={editing.titulo} onChange={e => setEditing({ ...editing, titulo: e.target.value })} placeholder="Ex.: Combinar um café" required maxLength={150} /></Field><div className="form-grid"><Field label="Data"><input type="date" value={editing.data} onChange={e => setEditing({ ...editing, data: e.target.value })} required /></Field><Field label="Prioridade"><select value={editing.priority || 'normal'} onChange={e => setEditing({ ...editing, priority: e.target.value as Reminder['priority'] })}><option value="normal">Normal</option><option value="alta">Alta</option></select></Field></div><Field label="Pessoa vinculada"><select value={editing.personId || ''} onChange={e => setEditing({ ...editing, personId: e.target.value || null })}><option value="">Sem pessoa vinculada</option>{data.people.filter(p => !p.deletedAt || p.id === editing.personId).map(p => <option key={p.id} value={p.id}>{p.nome}{p.archivedAt ? ' (arquivada)' : p.deletedAt ? ' (na lixeira)' : ''}</option>)}</select></Field><Field label="Repetir"><select value={editing.repeat || 'none'} onChange={e => setEditing({ ...editing, repeat: e.target.value as Reminder['repeat'] })}><option value="none">Não repetir</option><option value="daily">Todo dia</option><option value="weekly">Toda semana</option><option value="monthly">Todo mês</option><option value="yearly">Todo ano</option></select></Field><Field label="Detalhes"><textarea rows={3} value={editing.descricao || ''} onChange={e => setEditing({ ...editing, descricao: e.target.value })} placeholder="Anote os detalhes, se quiser." /></Field></Modal>}
    {deleting && <Confirm title="Excluir lembrete?" description="A ficha da pessoa vinculada não será alterada." danger confirmLabel="Excluir lembrete" onClose={() => setDeleting(null)} onConfirm={() => ctx.commit(d => ({ ...d, reminders: d.reminders.filter(r => r.id !== deleting) }), 'Lembrete excluído.')} />}
  </section>;
}