import { useState } from 'react';
import { Bell, CalendarClock, Check, Clock3, Edit3, Plus, Trash2 } from 'lucide-react';
import type { Reminder } from '../types';
import { useCatalog } from '../context';
import { addDays, formatDate, generateId, today } from '../store';
import { Avatar, Button, Confirm, EmptyState, Field, IconButton, Modal, PageTitle, SectionHeading } from './ui';

export default function Reminders({ compact = false }: { compact?: boolean }) {
  const ctx = useCatalog(), { data } = ctx;
  const [scope, setScope] = useState('pending'); const [editing, setEditing] = useState<Reminder | null>(null); const [deleting, setDeleting] = useState<string | null>(null);
  const filtered = [...data.reminders].filter(r => scope === 'all' || scope === 'done' ? scope === 'all' || r.concluido : scope === 'overdue' ? !r.concluido && r.data < today() : !r.concluido).sort((a, b) => Number(a.concluido) - Number(b.concluido) || a.data.localeCompare(b.data));
  const shown = compact ? filtered.slice(0, 4) : filtered;
  const create = () => setEditing({ id: generateId(), titulo: '', personId: null, data: today(), concluido: false, createdAt: new Date().toISOString(), priority: 'normal', descricao: '' });
  const save = () => { if (!editing?.titulo.trim() || !editing.data) return; const reminder = { ...editing, titulo: editing.titulo.trim() }; ctx.commit(d => ({ ...d, reminders: d.reminders.some(r => r.id === reminder.id) ? d.reminders.map(r => r.id === reminder.id ? reminder : r) : [...d.reminders, reminder] }), 'Lembrete salvo.'); setEditing(null); };
  const toggle = (r: Reminder) => ctx.commit(d => ({ ...d, reminders: d.reminders.map(x => x.id === r.id ? { ...x, concluido: !x.concluido } : x) }), r.concluido ? 'Lembrete reaberto.' : 'Lembrete concluído.');
  const snooze = (r: Reminder, days: number) => ctx.commit(d => ({ ...d, reminders: d.reminders.map(x => x.id === r.id ? { ...x, data: addDays(x.data < today() ? today() : x.data, days), concluido: false } : x) }), `Lembrete adiado por ${days} dia(s).`);
  return <section className={compact ? 'reminders-preview' : 'reminders-page'}>{compact ? <SectionHeading icon={Bell} title="Para não esquecer" action="Ver lembretes" onAction={() => ctx.navigate('reminders')} /> : <><PageTitle eyebrow="Um cuidado com as suas conexões" title="Lembretes" description="Pequenos lembretes para não deixar os bons momentos passarem."><Button variant="primary" onClick={create}><Plus size={18} />Novo lembrete</Button></PageTitle><div className="scope-tabs">{[['pending', 'Pendentes'], ['overdue', 'Atrasados'], ['done', 'Concluídos'], ['all', 'Todos']].map(([value, label]) => <button key={value} className={scope === value ? 'active' : ''} onClick={() => setScope(value)}>{label}</button>)}</div><p className="form-help"><Bell size={14} />Os lembretes são locais e aparecem ao abrir o app. Não há notificações em segundo plano.</p></>}
    <div className="reminder-list">{shown.map(r => { const person = data.people.find(p => p.id === r.personId); const overdue = !r.concluido && r.data < today(); return <div key={r.id} className={`reminder-row ${r.concluido ? 'completed' : ''}`}><button className={`complete-reminder ${r.concluido ? 'checked' : ''}`} onClick={() => toggle(r)} aria-label={r.concluido ? `Reabrir ${r.titulo}` : `Concluir ${r.titulo}`}>{r.concluido && <Check size={15} />}</button><div className="reminder-content"><button onClick={() => setEditing(r)}><strong>{r.titulo}</strong></button><span className={overdue ? 'overdue' : ''}><CalendarClock size={13} />{overdue ? 'Atrasado · ' : r.data === today() ? 'Hoje · ' : ''}{formatDate(r.data)}{r.priority === 'alta' && <small>Prioridade alta</small>}</span>{!compact && r.descricao && <p>{r.descricao}</p>}</div>{person && <button className="reminder-person" onClick={() => ctx.openPerson(person)}><Avatar person={person} size={31} /><span>{person.nome}{person.deletedAt && <small>Na lixeira</small>}</span></button>}<div className="reminder-actions">{!r.concluido && <details className="details-menu"><summary className="icon-btn" title="Adiar lembrete" aria-label="Adiar lembrete"><Clock3 size={16} /></summary><div className="dropdown-menu"><button onClick={() => snooze(r, 1)}>Adiar por 1 dia</button><button onClick={() => snooze(r, 7)}>Adiar por 7 dias</button></div></details>}<IconButton label="Editar lembrete" onClick={() => setEditing(r)}><Edit3 size={16} /></IconButton>{!compact && <IconButton label="Excluir lembrete" onClick={() => setDeleting(r.id)}><Trash2 size={16} /></IconButton>}</div></div>; })}</div>
    {!shown.length && (compact ? <div className="reminders-empty"><span><Bell size={17} />Tudo em dia. Crie um lembrete para um próximo encontro.</span><button className="text-action" onClick={create}><Plus size={14} />Adicionar lembrete</button></div> : <EmptyState icon={Bell} title={scope === 'done' ? 'Os concluídos aparecerão aqui' : 'Tudo em dia por aqui'} description="Crie lembretes com datas e pessoas vinculadas, e conclua quando terminar." action="Criar lembrete" onAction={create} />)}
    {editing && <Modal title={data.reminders.some(r => r.id === editing.id) ? 'Editar lembrete' : 'Novo lembrete'} onClose={() => setEditing(null)} footer={<><Button onClick={() => setEditing(null)}>Cancelar</Button><Button variant="primary" disabled={!editing.titulo.trim() || !editing.data} onClick={save}><Check size={16} />Salvar lembrete</Button></>}><Field label="O que você quer lembrar?"><input value={editing.titulo} onChange={e => setEditing({ ...editing, titulo: e.target.value })} placeholder="Ex.: Combinar um café" required maxLength={150} /></Field><div className="form-grid"><Field label="Data"><input type="date" value={editing.data} onChange={e => setEditing({ ...editing, data: e.target.value })} required /></Field><Field label="Prioridade"><select value={editing.priority || 'normal'} onChange={e => setEditing({ ...editing, priority: e.target.value as Reminder['priority'] })}><option value="normal">Normal</option><option value="alta">Alta</option></select></Field></div><Field label="Pessoa vinculada"><select value={editing.personId || ''} onChange={e => setEditing({ ...editing, personId: e.target.value || null })}><option value="">Sem pessoa vinculada</option>{data.people.filter(p => !p.deletedAt || p.id === editing.personId).map(p => <option key={p.id} value={p.id}>{p.nome}{p.archivedAt ? ' (arquivada)' : p.deletedAt ? ' (na lixeira)' : ''}</option>)}</select></Field><Field label="Detalhes"><textarea rows={3} value={editing.descricao || ''} onChange={e => setEditing({ ...editing, descricao: e.target.value })} placeholder="Anote os detalhes, se quiser." /></Field></Modal>}
    {deleting && <Confirm title="Excluir lembrete?" description="A ficha da pessoa vinculada não será alterada." danger confirmLabel="Excluir lembrete" onClose={() => setDeleting(null)} onConfirm={() => ctx.commit(d => ({ ...d, reminders: d.reminders.filter(r => r.id !== deleting) }), 'Lembrete excluído.')} />}
  </section>;
}