import { ArrowUpRight, Bell, BookOpen, ChevronRight, ClipboardList, FileText, Folder, Heart, Home, Image, Layers, LogOut, PlusCircle, Settings2, Shapes, Sparkles, Trophy, Users } from 'lucide-react';
import { useCatalog } from '../context';
import { isActive } from '../store';
import { Avatar, IconButton } from './ui';

export default function Sidebar() {
  const ctx = useCatalog(), { data, page } = ctx;
  const activeCount = data.people.filter(isActive).length;
  const pending = data.reminders.filter(r => !r.concluido).length;
  const nav = [{ id: 'home', label: 'Início', icon: Home }, { id: 'catalog', label: 'Catálogo', icon: Users, count: activeCount }, { id: 'ranking', label: 'Ranking', icon: Trophy }, { id: 'tierlists', label: 'Tierlists', icon: Layers }];
  const library = [{ id: 'add', label: 'Adicionar pessoa', icon: PlusCircle }, { id: 'gallery', label: 'Galeria', icon: Image }, { id: 'notes', label: 'Notas gerais', icon: FileText }, { id: 'folders', label: 'Pastas', icon: Folder }, { id: 'board', label: 'Quadro', icon: ClipboardList }, { id: 'stories', label: 'Stories / Fanfics', icon: BookOpen }, { id: 'reminders', label: 'Lembretes', icon: Bell, count: pending || undefined }, { id: 'tools', label: 'Organizar', icon: Shapes }];
  return <aside className="sidebar"><button className="brand" onClick={() => ctx.navigate('home')} aria-label="Catalog, ir para início"><span className="brand-symbol"><Heart size={23} fill="currentColor" strokeWidth={0} /></span><span>catalog<span className="brand-dot">.</span><small>seu universo pessoal</small></span></button>
    <nav aria-label="Menu principal"><p className="nav-label">Seu espaço</p>{nav.map(({ id, label, icon: Icon, count }) => <button key={id} className={`nav-item ${page === id ? 'active' : ''}`} onClick={() => ctx.navigate(id)} aria-current={page === id ? 'page' : undefined}><Icon size={19} strokeWidth={1.7} /><span>{label}</span>{count !== undefined && <small>{count}</small>}{page === id && count === undefined && <i />}</button>)}
      <p className="nav-label library-label">Sua biblioteca</p>{library.map(({ id, label, icon: Icon, count }) => { const active = page === id || id === 'tools' && ['taxonomy', 'collections', 'drafts', 'duplicates', 'activity'].includes(page); return <button key={id} className={`nav-item ${active ? 'active' : ''}`} onClick={() => ctx.navigate(id)} aria-current={active ? 'page' : undefined}><Icon size={19} strokeWidth={1.7} /><span>{label}</span>{count !== undefined && <small>{count}</small>}</button>; })}
    </nav>
    <div className="sidebar-bottom"><button className="new-features-link" onClick={() => ctx.navigate('guide')}><Sparkles size={17} /><span>Novidades do Catalog<small>26 formas de simplificar</small></span><ArrowUpRight size={14} /></button><button className={`nav-item ${page === 'settings' ? 'active' : ''}`} onClick={() => ctx.navigate('settings')}><Settings2 size={19} strokeWidth={1.7} /><span>Ajustes</span><ChevronRight size={14} /></button><div className="sidebar-profile"><button onClick={() => ctx.navigate('settings')}><Avatar src={data.settings.avatar} name={data.settings.profileName} size={38} /><span><strong>{data.settings.profileName}</strong><small>{ctx.demo ? 'Modo demonstração' : 'Perfil local'}</small></span></button><IconButton label={ctx.demo ? 'Sair da demonstração' : 'Sair da conta'} onClick={ctx.logout}><LogOut size={16} /></IconButton></div></div>
  </aside>;
}