import { useState } from 'react';
import { Bold, BookOpen, CalendarDays, Edit3, FileText, Italic, List, Plus, Search, Trash2 } from 'lucide-react';
import type { Story } from '../types';
import { useCatalog } from '../context';
import { formatDate, generateId, isAdult, normalizeText, today } from '../store';
import { Avatar, Button, CheckBox, Confirm, EmptyState, Field, IconButton, Modal, PageTitle } from './ui';

function StoryText({ text }: { text: string }) { return <div className="story-text">{text.split('\n').map((line, i) => <p key={i}>{line.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g).map((part, j) => part.startsWith('**') && part.endsWith('**') ? <strong key={j}>{part.slice(2, -2)}</strong> : part.startsWith('*') && part.endsWith('*') ? <em key={j}>{part.slice(1, -1)}</em> : <span key={j}>{part}</span>)}{!line && <br />}</p>)}</div>; }
export default function Stories() {
  const ctx = useCatalog(), { data } = ctx;
  const [query, setQuery] = useState(''); const [type, setType] = useState(''); const [person, setPerson] = useState('');
  const [editing, setEditing] = useState<Story | null>(null); const [reading, setReading] = useState<Story | null>(null); const [deleting, setDeleting] = useState<string | null>(null); const [adultConfirmed, setAdultConfirmed] = useState(false);
  const filtered = data.stories.filter(s => (!type || s.tipo === type) && (!person || s.personId === person) && normalizeText(`${s.titulo} ${s.conteudo}`).includes(normalizeText(query))).sort((a, b) => b.date.localeCompare(a.date));
  const create = () => { setEditing({ id: generateId(), titulo: '', tipo: 'detalhada', personId: null, conteudo: '', date: today() }); setAdultConfirmed(false); };
  const edit = (story: Story) => { setEditing({ ...story }); setAdultConfirmed(story.tipo === 'detalhada'); setReading(null); };
  const save = () => {
    if (!editing?.titulo.trim() || !editing.conteudo.trim()) return;
    const owner = data.people.find(p => p.id === editing.personId);
    if (editing.tipo !== 'detalhada' && (!adultConfirmed || owner && !isAdult(owner))) { ctx.notify('Histórias adultas exigem confirmação de maioridade e consentimento.', true); return; }
    ctx.commit(d => ({ ...d, stories: d.stories.some(s => s.id === editing.id) ? d.stories.map(s => s.id === editing.id ? { ...editing, titulo: editing.titulo.trim() } : s) : [{ ...editing, titulo: editing.titulo.trim() }, ...d.stories] }), 'História salva.'); setEditing(null);
  };
  const format = (start: string, end: string) => {
    const input = document.getElementById('story-content') as HTMLTextAreaElement | null; if (!input || !editing) return;
    const a = input.selectionStart, b = input.selectionEnd, value = editing.conteudo;
    setEditing({ ...editing, conteudo: value.slice(0, a) + start + (value.slice(a, b) || 'texto') + end + value.slice(b) });
    requestAnimationFrame(() => { input.focus(); input.setSelectionRange(a + start.length, (a === b ? a + 5 : b) + start.length); });
  };
  return <div className="stories-page"><PageTitle eyebrow="Um lugar para suas histórias" title="Stories / Fanfics" description="Anote um encontro, imagine uma história ou preserve um momento."><Button variant="primary" onClick={create}><Plus size={17} />Nova história</Button></PageTitle><div className="stories-toolbar"><div className="search-field"><Search size={17} /><input type="text" value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar no título ou no conteúdo..." aria-label="Buscar histórias" /></div><select aria-label="Tipo de história" value={type} onChange={e => setType(e.target.value)}><option value="">Todos os tipos</option><option value="detalhada">Detalhada</option><option value="picante">Picante</option><option value="sexual">Sexual</option></select><select aria-label="Pessoa da história" value={person} onChange={e => setPerson(e.target.value)}><option value="">Todas as pessoas</option>{data.people.map(p => <option value={p.id} key={p.id}>{p.nome}{p.deletedAt ? ' (na lixeira)' : ''}</option>)}</select></div><div className="stories-grid">{filtered.map(story => { const p = data.people.find(p => p.id === story.personId); return <article key={story.id} className="story-card"><div className="story-card-head"><span className="story-icon"><BookOpen size={20} /></span><span className="note-type">{story.tipo}</span><div><IconButton label="Editar história" onClick={() => edit(story)}><Edit3 size={15} /></IconButton><IconButton label="Excluir história" onClick={() => setDeleting(story.id)}><Trash2 size={15} /></IconButton></div></div><button className="story-open" onClick={() => setReading(story)}><h2>{story.titulo}</h2><p>{story.conteudo.replace(/\*/g, '')}</p></button><footer>{p ? <button className="story-person" onClick={() => ctx.openPerson(p)}><Avatar person={p} size={28} />{p.nome}</button> : <span className="muted small">Sem vínculo</span>}<time><CalendarDays size={12} />{formatDate(story.date)}</time></footer></article>; })}</div>{!filtered.length && <EmptyState icon={BookOpen} title="Toda boa história começa com uma linha" description="Crie sua primeira história. Ela fica guardada apenas neste dispositivo." action="Escrever história" onAction={create} />}
    {editing && <Modal title={data.stories.some(s => s.id === editing.id) ? 'Editar história' : 'Uma nova história'} onClose={() => setEditing(null)} wide footer={<><span className="muted small">{editing.conteudo.trim().split(/\s+/).filter(Boolean).length} palavras</span><Button onClick={() => setEditing(null)}>Cancelar</Button><Button variant="primary" disabled={!editing.titulo.trim() || !editing.conteudo.trim() || editing.tipo !== 'detalhada' && !adultConfirmed} onClick={save}><FileText size={16} />Salvar história</Button></>}><Field label="Título"><input value={editing.titulo} onChange={e => setEditing({ ...editing, titulo: e.target.value })} placeholder="Dê um nome à sua história" maxLength={150} /></Field><div className="form-grid"><Field label="Tipo"><select value={editing.tipo} onChange={e => { setEditing({ ...editing, tipo: e.target.value as Story['tipo'], personId: null }); setAdultConfirmed(false); }}><option value="detalhada">Detalhada</option><option value="picante">Picante (adultos)</option><option value="sexual">Sexual (adultos)</option></select></Field><Field label="Pessoa vinculada"><select value={editing.personId || ''} onChange={e => setEditing({ ...editing, personId: e.target.value || null })}><option value="">Sem vínculo</option>{data.people.filter(p => (!p.deletedAt || p.id === editing.personId) && (editing.tipo === 'detalhada' || isAdult(p))).map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field></div>{editing.tipo !== 'detalhada' && <CheckBox checked={adultConfirmed} onChange={() => setAdultConfirmed(!adultConfirmed)} label="Confirmo que todos os personagens são adultos. Tenho consentimento quando a história envolve pessoas reais." />}<div className="rich-editor"><div><IconButton label="Negrito" onClick={() => format('**', '**')}><Bold size={16} /></IconButton><IconButton label="Itálico" onClick={() => format('*', '*')}><Italic size={16} /></IconButton><IconButton label="Inserir item de lista" onClick={() => format('\n- ', '')}><List size={16} /></IconButton><small>Formatação leve com Markdown</small></div><textarea id="story-content" aria-label="Conteúdo da história" rows={10} value={editing.conteudo} onChange={e => setEditing({ ...editing, conteudo: e.target.value })} placeholder="Comece a escrever..." /></div><Field label="Data da história"><input type="date" value={editing.date.slice(0, 10)} onChange={e => setEditing({ ...editing, date: e.target.value })} /></Field></Modal>}
    {reading && <Modal title={reading.titulo} description={`${reading.tipo} · ${formatDate(reading.date)}`} onClose={() => setReading(null)} wide footer={<><Button onClick={() => setReading(null)}>Fechar</Button><Button onClick={() => edit(reading)}><Edit3 size={15} />Editar história</Button></>}><StoryText text={reading.conteudo} /></Modal>}
    {deleting && <Confirm title="Excluir esta história?" description="A ficha e as fotos da pessoa vinculada não serão alteradas. Você poderá desfazer nesta sessão." danger confirmLabel="Excluir história" onClose={() => setDeleting(null)} onConfirm={() => ctx.commit(d => ({ ...d, stories: d.stories.filter(s => s.id !== deleting) }), 'História excluída.')} />}
  </div>;
}